TRUNCATE TABLE Airlines;

INSERT INTO Airlines
SELECT AirlineCode, AirlineName, CallSign, Country
FROM (
SELECT AirlineCode, AirlineName, CallSign, Country
    ,n=ROW_NUMBER() OVER (PARTITION BY AirlineCode ORDER BY (SELECT NULL))
FROM (
SELECT '0B','Blue Air','BLUE TRANSPORT','Romania'
UNION ALL SELECT '0C','IBL Aviation','CATOVAIR','Mauritius'
UNION ALL SELECT '0D','Darwin Airline','DARWIN','Switzerland'
UNION ALL SELECT '0J','Jetclub','JETCLUB','Switzerland'
UNION ALL SELECT '1A','Amadeus Global Travel Distribution','AMADEUS','Spain'
UNION ALL SELECT '1B','Abacus International','','Singapore'
UNION ALL SELECT '1C','Electronic Data Systems','','Switzerland'
UNION ALL SELECT '1D','Radixx Solutions International','','United States'
UNION ALL SELECT '1E','Travelsky Technology','','China'
UNION ALL SELECT '1F','INFINI Travel Information','','Japan'
UNION ALL SELECT '1G','Galileo International','','United States'
UNION ALL SELECT '1H','Siren-Travel','','Russia'
UNION ALL SELECT '1I','Deutsche Rettungsflugwacht','CIVIL AIR AMBULANCE','Germany'
UNION ALL SELECT '1I','NetJets','EXECJET','United States'
UNION ALL SELECT '1I','Novair','NAVIGATOR','Sweden'
UNION ALL SELECT '1I','Pegasus Hava Tasimaciligi','Sunturk','Turkey'
UNION ALL SELECT '1I','Sierra Nevada Airlines','','United States'
UNION ALL SELECT '1I','Sky Trek International Airlines','PHAZER','United States'
UNION ALL SELECT '1K','Southern Cross Distribution','','Australia'
UNION ALL SELECT '1K','Sutra','','United States'
UNION ALL SELECT '1L','Open Skies Consultative Commission','OPEN SKIES','United States'
UNION ALL SELECT '1M','JSC Transport Automated Information Systems','','Russia'
UNION ALL SELECT '1N','Navitaire','','United States'
UNION ALL SELECT '1P','Worldspan','','United States'
UNION ALL SELECT '1Q','Sirena','','Russia'
UNION ALL SELECT '1R','Hainan Phoenix Information Systems','','China'
UNION ALL SELECT '1S','Sabre','','United States'
UNION ALL SELECT '1T','1Time Airline','NEXTIME','South Africa'
UNION ALL SELECT '1U','ITA Software','','United States'
UNION ALL SELECT '1U','Polyot Sirena','','Russia'
UNION ALL SELECT '1W','Wings Air','WINGS ABADI','Indonesia'
UNION ALL SELECT '1Y','Electronic Data Systems','','United States'
UNION ALL SELECT '1Z','Sabre Pacific','','Australia'
UNION ALL SELECT '2A','Deutsche Bahn','','Germany'
UNION ALL SELECT '2B','Aerocondor','AEROCONDOR','Portugal'
UNION ALL SELECT '2C','SNCF','','France'
UNION ALL SELECT '2D','Aero VIP','AVIP','Argentina'
UNION ALL SELECT '2F','Frontier Flying Service','FRONTIER-AIR','United States'
UNION ALL SELECT '2G','Cargoitalia','WHITE PELICAN','Italy'
UNION ALL SELECT '2G','San Juan Airlines','MARINER','United States'
UNION ALL SELECT '2H','Thalys','','Belgium'
UNION ALL SELECT '2J','Air Burkina','BURKINA','Burkina Faso'
UNION ALL SELECT '2K','Aerogal','AEROGAL','Ecuador'
UNION ALL SELECT '2L','Helvetic Airways','HELVETIC','Switzerland'
UNION ALL SELECT '2M','Moldavian Airlines','MOLDAVIAN','Moldova'
UNION ALL SELECT '2N','NextJet','NEXTJET','Sweden'
UNION ALL SELECT '2N','Yuzhmashavia','YUZMASH','Ukraine'
UNION ALL SELECT '2O','Air Salone','AIR SALONE','Sierra Leone'
UNION ALL SELECT '2P','Air Philippines','ORIENT PACIFIC','Philippines'
UNION ALL SELECT '2Q','Air Cargo Carriers','NIGHT CARGO','United States'
UNION ALL SELECT '2R','VIA Rail Canada','','Canada'
UNION ALL SELECT '2S','Island Express','SANDY ISLE','United States'
UNION ALL SELECT '2S','Star Equatorial Airlines','','Guinea'
UNION ALL SELECT '2T','Haiti Ambassador Airlines','','Haiti'
UNION ALL SELECT '2U','Air Guinee Express','FUTURE EXPRESS','Guinea'
UNION ALL SELECT '2V','Amtrak','','United States'
UNION ALL SELECT '2W','Welcome Air','WELCOMEAIR','Austria'
UNION ALL SELECT '2Z','Chang''an Airlines','CHANGAN','China'
UNION ALL SELECT '3B','Central Connect Airlines','','Czech Republic'
UNION ALL SELECT '3C','Calima Aviación','CALIMA','Spain'
UNION ALL SELECT '3C','RegionsAir','CORP-X','United States'
UNION ALL SELECT '3G','Atlant-Soyuz Airlines','ATLANT-SOYUZ','Russia'
UNION ALL SELECT '3J','Air Alliance','LIAISON','Canada'
UNION ALL SELECT '3J','Zip','ZIPPER','Canada'
UNION ALL SELECT '3K','Jetstar Asia Airways','JETSTAR ASIA','Singapore'
UNION ALL SELECT '3N','Air Urga','URGA','Ukraine'
UNION ALL SELECT '3P','Tiara Air','TIARA','Aruba'
UNION ALL SELECT '3Q','China Yunnan Airlines','YUNNAN','China'
UNION ALL SELECT '3R','Moskovia Airlines','GROMOV AIRLINE','Russia'
UNION ALL SELECT '3S','Aerologic','GERMAN CARGO','Germany'
UNION ALL SELECT '3S','Aeroland Airways','','Greece'
UNION ALL SELECT '3T','Turan Air','TURAN','Azerbaijan'
UNION ALL SELECT '3U','Sichuan Airlines','SI CHUAN','China'
UNION ALL SELECT '3V','TNT Airways','QUALITY','Belgium'
UNION ALL SELECT '3W','Euromanx Airways','EUROMANX','Austria'
UNION ALL SELECT '3W','Wanair','WANAIR','French Polynesia'
UNION ALL SELECT '4A','Air Kiribati','','Kiribati'
UNION ALL SELECT '4C','Aires, Aerovías de Integración Regional, S.A.','AIRES','Colombia'
UNION ALL SELECT '4D','Air Sinai','AIR SINAI','Egypt'
UNION ALL SELECT '4F','Air City','AIRCITY','Germany'
UNION ALL SELECT '4G','Gazpromavia','GAZPROMAVIA','Russia'
UNION ALL SELECT '4G','Advance Leasing Company','','United States'
UNION ALL SELECT '4H','United Airways','UNITED BANGLADESH','Bangladesh'
UNION ALL SELECT '4K','Askari Aviation','AL-ASS','Pakistan'
UNION ALL SELECT '4M','Aero 2000','LAN AR','Argentina'
UNION ALL SELECT '4N','Air North Charter - Canada','AIR NORTH','Canada'
UNION ALL SELECT '4R','Hamburg International','HAMBURG JET','Germany'
UNION ALL SELECT '4S','Finalair Congo','FINALAIR CONGO','Republic of the Congo'
UNION ALL SELECT '4T','Belair Airlines','BELAIR','Switzerland'
UNION ALL SELECT '4U','Germanwings','GERMAN WINGS','Germany'
UNION ALL SELECT '4Y','Airbus France','AIRBUS FRANCE','France'
UNION ALL SELECT '4Y','Yute Air Alaska','','United States'
UNION ALL SELECT '5A','Alpine Air Express','ALPINE AIR','United States'
UNION ALL SELECT '5C','CAL Cargo Air Lines','CAL','Israel'
UNION ALL SELECT '5D','Aerolitoral','COSTERA','Mexico'
UNION ALL SELECT '5D','DonbassAero','DONBASS AERO','Ukraine'
UNION ALL SELECT '5F','Arctic Circle Air Service','AIR ARCTIC','United States'
UNION ALL SELECT '5G','Skyservice Airlines','SKYTOUR','Canada'
UNION ALL SELECT '5J','Cebu Pacific','CEBU AIR','Philippines'
UNION ALL SELECT '5K','Hi Fly','SKY FLYER','Portugal'
UNION ALL SELECT '5L','Aerosur','AEROSUR','Bolivia'
UNION ALL SELECT '5M','Sibaviatrans','SIBAVIA','Russia'
UNION ALL SELECT '5N','Nordavia','ARCHANGELSK AIR','Russia'
UNION ALL SELECT '5O','Europe Airpost','FRENCH POST','France'
UNION ALL SELECT '5T','Canadian North','EMPRESS','Canada'
UNION ALL SELECT '5V','Lviv Airlines','UKRAINE WEST','Ukraine'
UNION ALL SELECT '5W','Astraeus','FLYSTAR','United Kingdom'
UNION ALL SELECT '5W','Iceland Express','FLYSTAR','Iceland'
UNION ALL SELECT '5X','United Parcel Service','UPS','United States'
UNION ALL SELECT '5Y','Atlas Air','GIANT','United States'
UNION ALL SELECT '5Z','Airfreight Express','','United Kingdom'
UNION ALL SELECT '5Z','Bismillah Airlines','BISMILLAH','Bangladesh'
UNION ALL SELECT '5Z','VivaColombia','VivaColombia','Colombia'
UNION ALL SELECT '6A','Aviacsa','AVIACSA','Mexico'
UNION ALL SELECT '6B','TUIfly Nordic','BLUESCAN','Sweden'
UNION ALL SELECT '6E','IndiGo Airlines','IFLY','India'
UNION ALL SELECT '6G','Air Wales','RED DRAGON','United Kingdom'
UNION ALL SELECT '6H','Israir','ISRAIR','Israel'
UNION ALL SELECT '6I','International Business Air','INTERBIZ','Sweden'
UNION ALL SELECT '6J','Skynet Asia Airways','NEWSKY','Japan'
UNION ALL SELECT '6K','Asian Spirit','ASIAN SPIRIT','Philippines'
UNION ALL SELECT '6N','Nordic Regional','NORTH RIDER','Sweden'
UNION ALL SELECT '6P','Club Air','CLUBAIR','Italy'
UNION ALL SELECT '6Q','Slovak Airlines','SLOV LINE','Slovakia'
UNION ALL SELECT '6R','Alrosa Mirny Air Enterprise','MIRNY','Russia'
UNION ALL SELECT '6U','Air Cargo Germany','LOADMASTER','Germany'
UNION ALL SELECT '6U','Air Ukraine','AIR UKRAINE','Ukraine'
UNION ALL SELECT '6V','Air Vegas','AIR VEGAS','United States'
UNION ALL SELECT '6V','Axis Airways','AXIS','France'
UNION ALL SELECT '6V','Mars RK','AVIAMARS','Ukraine'
UNION ALL SELECT '6W','Saratov Aviation Division','SARATOV AIR','Russia'
UNION ALL SELECT '6Z','Ukrainian Cargo Airways','CARGOTRANS','Ukraine'
UNION ALL SELECT '7A','Aztec Worldwide Airlines','','United States'
UNION ALL SELECT '7B','Krasnojarsky Airlines','KRASNOJARSKY AIR','Russia'
UNION ALL SELECT '7C','Coyne Aviation','COYNE AIR','United Kingdom'
UNION ALL SELECT '7C','Jeju Air','JEJU AIR','Republic of Korea'
UNION ALL SELECT '7E','Sylt Air GmbH','SYLT-AIR','Germany'
UNION ALL SELECT '7F','First Air','FIRST AIR','Canada'
UNION ALL SELECT '7G','Star Flyer','STARFLYER','Japan'
UNION ALL SELECT '7K','Kogalymavia Air Company','KOGALYM','Russia'
UNION ALL SELECT '7L','Sun D''Or','ECHO ROMEO','Israel'
UNION ALL SELECT '7M','Mistral Air','AIRMERCI','Italy'
UNION ALL SELECT '7N','Centavia','','Serbia'
UNION ALL SELECT '7O','Galaxy Air','GALAXY','Kyrgyzstan'
UNION ALL SELECT '7R','BRA-Transportes Aéreos','BRA-TRANSPAEREOS','Brazil'
UNION ALL SELECT '7S','Ryan Air Service','ARCTIC TRANSPORT','United States'
UNION ALL SELECT '7T','Air Glaciers','AIR GLACIERS','Switzerland'
UNION ALL SELECT '7T','Tobruk Air','TOBRUK AIR','Libya'
UNION ALL SELECT '7W','Wayraperú','WAYRAPERÚ','Peru'
UNION ALL SELECT '8A','Atlas Blue','ATLAS BLUE','Morocco'
UNION ALL SELECT '8B','Caribbean Star Airlines','CARIB STAR','Antigua and Barbuda'
UNION ALL SELECT '8C','Air Transport International','AIR TRANSPORT','United States'
UNION ALL SELECT '8C','Air Horizon','HORIZON TOGO','Togo'
UNION ALL SELECT '8C','Shanxi Airlines','SHANXI','China'
UNION ALL SELECT '8D','Expo Aviation','EXPOAVIA','Sri Lanka'
UNION ALL SELECT '8D','Servant Air','','United States'
UNION ALL SELECT '8D','Astair','','Russian Federation'
UNION ALL SELECT '8E','Bering Air','BERING AIR','United States'
UNION ALL SELECT '8F','Fischer Air','FISCHER','Czech Republic'
UNION ALL SELECT '8H','Heli France','HELIFRANCE','France'
UNION ALL SELECT '8I','Myway Airlines','','Italy'
UNION ALL SELECT '8J','Komiinteravia','KOMIINTER','Russia'
UNION ALL SELECT '8L','Cargo Plus Aviation','','United Arab Emirates'
UNION ALL SELECT '8L','Redhill Aviation','REDAIR','United Kingdom'
UNION ALL SELECT '8M','Maxair','MAXAIR','Sweden'
UNION ALL SELECT '8M','Myanmar Airways International','assignment postponed','Myanmar'
UNION ALL SELECT '8N','Barents AirLink','NORDFLIGHT','Sweden'
UNION ALL SELECT '8O','West Coast Air','COAST AIR','Canada'
UNION ALL SELECT '8P','Pacific Coastal Airline','PASCO','Canada'
UNION ALL SELECT '8Q','Onur Air','ONUR AIR','Turkey'
UNION ALL SELECT '8Q','Princess Air','',''
UNION ALL SELECT '8Q','Baker Aviation','BAKER AVIATION','United States'
UNION ALL SELECT '8R','TRIP Linhas Aéreas','TRIP','Brazil'
UNION ALL SELECT '8S','Scorpio Aviation','',''
UNION ALL SELECT '8T','Air Tindi','','Canada'
UNION ALL SELECT '8U','Afriqiyah Airways','AFRIQIYAH','Libya'
UNION ALL SELECT '8V','Astral Aviation','ASTRAL CARGO','Kenya'
UNION ALL SELECT '8V','Wright Air Service','WRIGHT FLYER','United States'
UNION ALL SELECT '8W','Private Wings Flugcharter','PRIVATE WINGS','Germany'
UNION ALL SELECT '8W','BAX Global','',''
UNION ALL SELECT '8Y','Air Burundi','AIR-BURUNDI','Burundi'
UNION ALL SELECT '8Y','China Postal Airlines','CHINA POST','China'
UNION ALL SELECT '8Z','Wizz Air Bulgaria','WIZZBUL','Bulgaria'
UNION ALL SELECT '9c','Spring Airlines','AIR SPRING','China'
UNION ALL SELECT '9E','Pinnacle Airlines','FLAGSHIP','United States'
UNION ALL SELECT '9I','Helitrans','SCANBIRD','Norway'
UNION ALL SELECT '9I','Thai Sky Airlines','THAI SKY','Thailand'
UNION ALL SELECT '9K','Cape Air','CAIR','United States'
UNION ALL SELECT '9L','Colgan Air','COLGAN','United States'
UNION ALL SELECT '9O','National Airways Cameroon','','Cameroon'
UNION ALL SELECT '9Q','PB Air','PEEBEE AIR','Thailand'
UNION ALL SELECT '9R','Phuket Air','PHUKET AIR','Thailand'
UNION ALL SELECT '9T','Transwest Air','ATHABASKA','Canada'
UNION ALL SELECT '9U','Air Moldova','AIR MOLDOVA','Moldova'
UNION ALL SELECT '9W','Jet Airways','JET AIRWAYS','India'
UNION ALL SELECT '9Y','Fly Georgia','FLYGEORGIA','GEORGIA'
UNION ALL SELECT 'A2','Cielos Airlines','CIELOS','Peru'
UNION ALL SELECT 'A3','Aegean Airlines','AEGEAN','Greece'
UNION ALL SELECT 'A4','Southern Winds Airlines','SOUTHERN WINDS','Argentina'
UNION ALL SELECT 'A5','Airlinair','AIRLINAIR','France'
UNION ALL SELECT 'A6','Air Alps Aviation','ALPAV','Austria'
UNION ALL SELECT 'A7','Air Plus Comet','RED COMET','Spain'
UNION ALL SELECT 'A8','Benin Golf Air','BENIN GOLF','Benin'
UNION ALL SELECT 'A9','Georgian Airways','TAMAZI','Georgia'
UNION ALL SELECT 'AA','American Airlines','AMERICAN','United States'
UNION ALL SELECT 'AB','Air Berlin','AIR BERLIN','Germany'
UNION ALL SELECT 'AC','Air Canada','AIR CANADA','Canada'
UNION ALL SELECT 'AD','Air Paradise International','RADISAIR','Indonesia'
UNION ALL SELECT 'AD','Azul Linhas Aéreas Brasileiras','Azul','Brazil'
UNION ALL SELECT 'AE','Mandarin Airlines','MANDARIN','Taiwan'
UNION ALL SELECT 'AF','Air France','AIRFRANS','France'
UNION ALL SELECT 'AH','Air Algérie','AIR ALGERIE','Algeria'
UNION ALL SELECT 'AI','Air India Limited','AIRINDIA','India'
UNION ALL SELECT 'AJ','Aero Contractors','AEROLINE','Nigeria'
UNION ALL SELECT 'AK','AirAsia','ASIAN EXPRESS','Malaysia'
UNION ALL SELECT 'AK','Air Bridge Carriers','AIRBRIDGE','United Kingdom'
UNION ALL SELECT 'AL','Skywalk Airlines','SKYWAY-EX','United States'
UNION ALL SELECT 'AL','TransAVIAexport Airlines','TRANSEXPORT','Belarus'
UNION ALL SELECT 'AM','Aeroméxico','AEROMEXICO','Mexico'
UNION ALL SELECT 'AN','Ansett Australia','ANSETT','Australia'
UNION ALL SELECT 'AO','Australian Airlines','AUSTRALIAN','Australia'
UNION ALL SELECT 'AP','Air One','HERON','Italy'
UNION ALL SELECT 'AP','Airbus Industrie','AIRBUS INDUSTRIE','France'
UNION ALL SELECT 'AQ','Aloha Air Cargo','ALOHA','United States'
UNION ALL SELECT 'AQ','Aloha Airlines','ALOHA','United States'
UNION ALL SELECT 'AQ','MAP-Management and Planung','MAPJET','Austria'
UNION ALL SELECT 'AR','Aerolíneas Argentinas','ARGENTINA','Argentina'
UNION ALL SELECT 'AS','Alaska Airlines, Inc.','ALASKA','United States'
UNION ALL SELECT 'AT','Royal Air Maroc','ROYALAIR MAROC','Morocco'
UNION ALL SELECT 'AU','Austral Líneas Aéreas','AUSTRAL','Argentina'
UNION ALL SELECT 'AV','Avianca - Aerovías Nacionales de Colombia, S.A.','AVIANCA','Colombia'
UNION ALL SELECT 'AW','Africa World Airlines','BLACKSTAR','Ghana'
UNION ALL SELECT 'AW','CHC Airways','SCHREINER','Netherlands'
UNION ALL SELECT 'AW','Dirgantara Air Service','DIRGANTARA','Indonesia'
UNION ALL SELECT 'AX','Trans States Airlines','WATERSKI','United States'
UNION ALL SELECT 'AY','Finnair','FINNAIR','Finland'
UNION ALL SELECT 'AZ','Alitalia','ALITALIA','Italy'
UNION ALL SELECT 'B2','Belavia Belarusian Airlines','BELARUS AVIA','Belarus'
UNION ALL SELECT 'B3','Bellview Airlines','BELLVIEW AIRLINES','Nigeria'
UNION ALL SELECT 'B4','BACH Flugbetriebsges','BACH','Austria'
UNION ALL SELECT 'B4','Bankair','BANKAIR','United States'
UNION ALL SELECT 'B5','Flightline','FLIGHTLINE','United Kingdom'
UNION ALL SELECT 'B6','JetBlue Airways','JETBLUE','United States'
UNION ALL SELECT 'B8','Eritrean Airlines','ERITREAN','Eritrea'
UNION ALL SELECT 'B9','Air Bangladesh','AIR BANGLA','Bangladesh'
UNION ALL SELECT 'BA','British Airways','SPEEDBIRD','United Kingdom'
UNION ALL SELECT 'BB','Seaborne Airlines','SEABORNE','United States'
UNION ALL SELECT 'BC','Skymark Airlines','SKYMARK','Japan'
UNION ALL SELECT 'BD','BMI','MIDLAND','United Kingdom'
UNION ALL SELECT 'BE','Flybe','JERSEY','United Kingdom'
UNION ALL SELECT 'BF','Aero-Service','CONGOSERV','Republic of the Congo'
UNION ALL SELECT 'BF','Bluebird Cargo','BLUE CARGO','Iceland'
UNION ALL SELECT 'BG','Biman Bangladesh Airlines','BANGLADESH','Bangladesh'
UNION ALL SELECT 'BH','Hawkair','','Canada'
UNION ALL SELECT 'BI','Royal Brunei Airlines','BRUNEI','Brunei'
UNION ALL SELECT 'BJ','Nouvel Air Tunisie','NOUVELAIR','Tunisia'
UNION ALL SELECT 'BK','Potomac Air','DISTRICT','United States'
UNION ALL SELECT 'BL','Pacific Airlines','PACIFIC AIRLINES','Vietnam'
UNION ALL SELECT 'BM','Air Sicilia','','Italy'
UNION ALL SELECT 'BM','Bayu Indonesia Air','BAYU','Indonesia'
UNION ALL SELECT 'BN','Braniff International Airways','Braniff','United States'
UNION ALL SELECT 'BN','Forward Air International Airlines','','United States'
UNION ALL SELECT 'BN','Horizon Airlines','HORIZON','Australia'
UNION ALL SELECT 'BO','Bouraq Indonesia Airlines','BOURAQ','Indonesia'
UNION ALL SELECT 'BP','Air Botswana','BOTSWANA','Botswana'
UNION ALL SELECT 'BQ','Aeromar Lineas Aereas Dominicanas','BRAVO QUEBEC','Dominican Republic'
UNION ALL SELECT 'BR','EVA Air','EVA','Taiwan'
UNION ALL SELECT 'BS','British International Helicopters','BRINTEL','United Kingdom'
UNION ALL SELECT 'BT','Air Baltic','AIRBALTIC','Latvia'
UNION ALL SELECT 'BV','Blue Panorama Airlines','BLUE PANOROMA','Italy'
UNION ALL SELECT 'BW','Caribbean Airlines','CARIBBEAN','Trinidad and Tobago'
UNION ALL SELECT 'BX','Air Busan','','Republic of Korea'
UNION ALL SELECT 'BX','Coast Air','COAST CENTER','Norway'
UNION ALL SELECT 'BY','Thomson Airways','TOMSON','United Kingdom'
UNION ALL SELECT 'BZ','Blue Dart Aviation','BLUE DART','India'
UNION ALL SELECT 'BZ','Keystone Air Service','KEYSTONE','Canada'
UNION ALL SELECT 'C0','Centralwings','CENTRALWINGS','Poland'
UNION ALL SELECT 'C3','Independent Carrier (ICAR)','ICAR','Ukraine'
UNION ALL SELECT 'C4','Zimex Aviation','ZIMEX','Switzerland'
UNION ALL SELECT 'C5','CommutAir','COMMUTAIR','United States'
UNION ALL SELECT 'C6','CanJet','CANJET','Canada'
UNION ALL SELECT 'C7','Rico Linhas Aéreas','RICO','Brazil'
UNION ALL SELECT 'C8','Cargolux Italia','CARGO MED','Italy'
UNION ALL SELECT 'C8','Chicago Express Airlines','WINDY CITY','United States'
UNION ALL SELECT 'C9','Cirrus Airlines','CIRRUS AIR','Germany'
UNION ALL SELECT 'CA','Air China','AIR CHINA','China'
UNION ALL SELECT 'CB','Kalitta Charters II','KALITTA','United States'
UNION ALL SELECT 'CC','Air Atlanta Icelandic','ATLANTA','Iceland'
UNION ALL SELECT 'CC','Macair Airlines','','Australia'
UNION ALL SELECT 'CD','Alliance Air','ALLIED','India'
UNION ALL SELECT 'CE','Nationwide Airlines','NATIONWIDE','South Africa'
UNION ALL SELECT 'CF','City Airline','SWEDESTAR','Sweden'
UNION ALL SELECT 'CG','Airlines PNG','BALUS','Papua New Guinea'
UNION ALL SELECT 'CH','Bemidji Airlines','BEMIDJI','United States'
UNION ALL SELECT 'CI','China Airlines','DYNASTY','Taiwan'
UNION ALL SELECT 'CJ','China Northern Airlines','CHINA NORTHERN','China'
UNION ALL SELECT 'CJ','CityFlyer Express','FLYER','United Kingdom'
UNION ALL SELECT 'CK','China Cargo Airlines','CARGO KING','China'
UNION ALL SELECT 'CL','Lufthansa CityLine','HANSALINE','Germany'
UNION ALL SELECT 'CM','Copa Airlines','COPA','Panama'
UNION ALL SELECT 'CN','Islands Nationair','','Papua New Guinea'
UNION ALL SELECT 'CN','Westward Airways','WESTWARD','United States'
UNION ALL SELECT 'CO','Continental Airlines','CONTINENTAL','United States'
UNION ALL SELECT 'CO','Continental Express','JETLINK','United States'
UNION ALL SELECT 'CP','Canadian Airlines','CANADIAN','Canada'
UNION ALL SELECT 'CP','Compass Airlines','Compass Rose','United States'
UNION ALL SELECT 'CQ','Sunshine Express Airlines','','Australia'
UNION ALL SELECT 'CR','OAG','','United Kingdom'
UNION ALL SELECT 'CS','Continental Micronesia','AIR MIKE','United States'
UNION ALL SELECT 'CT','Civil Air Transport','Mandarin','Taiwan'
UNION ALL SELECT 'CU','Cubana de Aviación','CUBANA','Cuba'
UNION ALL SELECT 'CV','Air Chathams','CHATHAM','New Zealand'
UNION ALL SELECT 'CV','Cargolux','CARGOLUX','Luxembourg'
UNION ALL SELECT 'CW','Air Marshall Islands','AIR MARSHALLS','Marshall Islands'
UNION ALL SELECT 'CX','Cathay Pacific','CATHAY','Hong Kong SAR of China'
UNION ALL SELECT 'CY','Cyprus Airways','CYPRUS','Cyprus'
UNION ALL SELECT 'CZ','China Southern Airlines','CHINA SOUTHERN','China'
UNION ALL SELECT 'D3','Daallo Airlines','DALO AIRLINES','Djibouti'
UNION ALL SELECT 'D4','Alidaunia','ALIDA','Italy'
UNION ALL SELECT 'D5','Dauair','DAUAIR','Germany'
UNION ALL SELECT 'D6','Interair South Africa','INLINE','South Africa'
UNION ALL SELECT 'D7','AirAsia X','XANADU','Malaysia'
UNION ALL SELECT 'D7','FlyAsianXpress','FAX AIR','Malaysia'
UNION ALL SELECT 'D8','Djibouti Airlines','DJIBOUTI AIR','Djibouti'
UNION ALL SELECT 'D9','Donavia','DONAVIA','Russia'
UNION ALL SELECT 'DA','Air Georgia','AIR GEORGIA','Georgia'
UNION ALL SELECT 'DB','Brit Air','BRITAIR','France'
UNION ALL SELECT 'DC','Golden Air','GOLDEN','Sweden'
UNION ALL SELECT 'DD','Nok Air','NOK AIR','Thailand'
UNION ALL SELECT 'DE','Condor Flugdienst','CONDOR','Germany'
UNION ALL SELECT 'DG','South East Asian Airlines','SEAIR','Philippines'
UNION ALL SELECT 'DH','Discovery Airways','DISCOVERY AIRWAYS','United States'
UNION ALL SELECT 'DH','Independence Air','INDEPENDENCE AIR','United States'
UNION ALL SELECT 'DI','Dba','SPEEDWAY','Germany'
UNION ALL SELECT 'DJ','Pacific Blue','BLUEBIRD','New Zealand'
UNION ALL SELECT 'DJ','Polynesian Blue','POLYBLUE','New Zealand'
UNION ALL SELECT 'DJ','Virgin Australia','VIRGIN','Australia'
UNION ALL SELECT 'DJ','Virgin Blue Holdings','BLUEY','Australia'
UNION ALL SELECT 'DK','Eastland Air','','Australia'
UNION ALL SELECT 'DL','Delta Air Lines','DELTA','United States'
UNION ALL SELECT 'DM','Maersk','','Denmark'
UNION ALL SELECT 'DO','Dominicana de Aviación','DOMINICANA','Dominican Republic'
UNION ALL SELECT 'DP','First Choice Airways','JETSET','United Kingdom'
UNION ALL SELECT 'DQ','Coastal Air','U.S. Virgin Islands','United States'
UNION ALL SELECT 'DR','Air Mediterranee','MEDITERRANEE','France'
UNION ALL SELECT 'DT','TAAG Angola Airlines','DTA','Angola'
UNION ALL SELECT 'DU','Hemus Air','HEMUS AIR','Bulgaria'
UNION ALL SELECT 'DV','Lufttaxi Fluggesellschaft','Garfield','Germany'
UNION ALL SELECT 'DV','Nantucket Airlines','ACK AIR','United States'
UNION ALL SELECT 'DW','Aero-Charter Ukraine','CHARTER UKRAINE','Ukraine'
UNION ALL SELECT 'DX','DAT Danish Air Transport','DANISH','Denmark'
UNION ALL SELECT 'DY','Norwegian Air Shuttle','NOR SHUTTLE','Norway'
UNION ALL SELECT 'E0','Eos Airlines','NEW DAWN','United States'
UNION ALL SELECT 'E1','Everbread','','United Kingdom'
UNION ALL SELECT 'E2','Kampuchea Airlines','KAMPUCHEA','Cambodia'
UNION ALL SELECT 'E2','Rio Grande Air','GRANDE','United States'
UNION ALL SELECT 'E3','Domodedovo Airlines','DOMODEDOVO','Russia'
UNION ALL SELECT 'E4','Aero Asia International','AERO ASIA','Pakistan'
UNION ALL SELECT 'E5','Samara Airlines','BERYOZA','Russia'
UNION ALL SELECT 'E6','Bringer Air Cargo Taxi Aéreo','','Brazil'
UNION ALL SELECT 'E7','Estafeta Carga Aérea','','Mexico'
UNION ALL SELECT 'E7','European Aviation Air Charter','EUROCHARTER','United Kingdom'
UNION ALL SELECT 'E8','Alpi Eagles','ALPI EAGLES','Italy'
UNION ALL SELECT 'E9','Boston-Maine Airways','CLIPPER CONNECTION','United States'
UNION ALL SELECT 'EA','European Air Express','STAR WING','Germany'
UNION ALL SELECT 'EC','Avialeasing Aviation Company','TWINARROW','Uzbekistan'
UNION ALL SELECT 'ED','Airblue','PAKBLUE','Pakistan'
UNION ALL SELECT 'EE','Aero Airlines','REVAL','Estonia'
UNION ALL SELECT 'EF','Far Eastern Air Transport','Far Eastern','Taiwan'
UNION ALL SELECT 'EG','Japan Asia Airways','ASIA','Japan'
UNION ALL SELECT 'EH','Air Nippon Network Co. Ltd.','ALFA WING','Japan'
UNION ALL SELECT 'EH','SAETA','SAETA','Ecuador'
UNION ALL SELECT 'EI','Aer Lingus','SHAMROCK','Ireland'
UNION ALL SELECT 'EJ','New England Airlines','NEW ENGLAND','United States'
UNION ALL SELECT 'EK','Emirates Airline','EMIRATES','United Arab Emirates'
UNION ALL SELECT 'EL','Air Nippon','ANK AIR','Japan'
UNION ALL SELECT 'EM','Empire Airlines','EMPIRE AIR','United States'
UNION ALL SELECT 'EM','Aero Benin','AEROBEN','Benin'
UNION ALL SELECT 'EN','Air Dolomiti','DOLOMITI','Italy'
UNION ALL SELECT 'EO','Express One International','LONGHORN','United States'
UNION ALL SELECT 'EO','Hewa Bora Airways','ALLCONGO','Democratic Republic of the Congo'
UNION ALL SELECT 'EP','Iran Aseman Airlines','ASEMAN','Iran'
UNION ALL SELECT 'EQ','TAME','TAME','Ecuador'
UNION ALL SELECT 'ER','Astar Air Cargo','D-H-L','United States'
UNION ALL SELECT 'ES','DHL International','DILMUN','Bahrain'
UNION ALL SELECT 'ET','Ethiopian Airlines','ETHIOPIAN','Ethiopia'
UNION ALL SELECT 'EU','Empresa Ecuatoriana De Aviación','ECUATORIANA','Ecuador'
UNION ALL SELECT 'EV','Atlantic Southeast Airlines','ACEY','United States'
UNION ALL SELECT 'EV','ExpressJet','ACEY','United States'
UNION ALL SELECT 'EW','Eurowings','EUROWINGS','Germany'
UNION ALL SELECT 'EX','Air Santo Domingo','AERO DOMINGO','Dominican Republic'
UNION ALL SELECT 'EY','Eagle Air','FLYING EAGLE','Tanzania'
UNION ALL SELECT 'EY','Etihad Airways','ETIHAD','United Arab Emirates'
UNION ALL SELECT 'EZ','Evergreen International Airlines','EVERGREEN','United States'
UNION ALL SELECT 'EZ','Sun Air of Scandinavia','SUNSCAN','Denmark'
UNION ALL SELECT 'F2','Fly Air','FLY WORLD','Turkey'
UNION ALL SELECT 'F3','Faso Airways','FASO','Burkina Faso'
UNION ALL SELECT 'F4','Albarka Air','AL-AIR','Nigeria'
UNION ALL SELECT 'F5','Cosmic Air','COSMIC AIR','Nepal'
UNION ALL SELECT 'F6','Faroejet','ROCKROSE','Faroe Islands'
UNION ALL SELECT 'F7','Flybaboo','BABOO','Switzerland'
UNION ALL SELECT 'F9','Frontier Airlines','FRONTIER FLIGHT','United States'
UNION ALL SELECT 'FA','Safair','CARGO','South Africa'
UNION ALL SELECT 'FB','Bulgaria Air','FLYING BULGARIA','Bulgaria'
UNION ALL SELECT 'FC','Finncomm Airlines','WESTBIRD','Finland'
UNION ALL SELECT 'FD','Thai AirAsia','THAI ASIA','Thailand'
UNION ALL SELECT 'FE','Primaris Airlines','WHITECAP','United States'
UNION ALL SELECT 'FF','Airshop','','Netherlands'
UNION ALL SELECT 'FG','Ariana Afghan Airlines','ARIANA','Afghanistan'
UNION ALL SELECT 'FH','Freebird Airlines','FREEBIRD AIR','Turkey'
UNION ALL SELECT 'FH','Futura International Airways','FUTURA','Spain'
UNION ALL SELECT 'FI','Icelandair','ICEAIR','Iceland'
UNION ALL SELECT 'FJ','Air Pacific','PACIFIC','Fiji'
UNION ALL SELECT 'FK','Africa West','WEST TOGO','Togo'
UNION ALL SELECT 'FL','AirTran Airways','CITRUS','United States'
UNION ALL SELECT 'FM','Shanghai Airlines','SHANGHAI AIR','China'
UNION ALL SELECT 'FN','Regional Air Lines','MAROC REGIONAL','Morocco'
UNION ALL SELECT 'FO','Airlines of Tasmania','AIRTAS','Australia'
UNION ALL SELECT 'FP','Freedom Air','FREEDOM','United States'
UNION ALL SELECT 'FQ','Thomas Cook Airlines','THOMAS COOK','Belgium'
UNION ALL SELECT 'FR','Ryanair','RYANAIR','Ireland'
UNION ALL SELECT 'FS','Itali Airlines','SPADA','Italy'
UNION ALL SELECT 'FS','Servicios de Transportes Aéreos Fueguinos','FUEGUINO','Argentina'
UNION ALL SELECT 'FT','Siem Reap Airways','SIEMREAP AIR','Cambodia'
UNION ALL SELECT 'FV','Pulkovo Aviation Enterprise','PULKOVO','Russia'
UNION ALL SELECT 'FV','Rossiya','RUSSIA','Russia'
UNION ALL SELECT 'FW','Ibex Airlines','IBEX','Japan'
UNION ALL SELECT 'FX','Federal Express','FEDEX','United States'
UNION ALL SELECT 'FY','Firefly','FIREFLY','Malaysia'
UNION ALL SELECT 'FY','Northwest Regional Airlines','','Australia'
UNION ALL SELECT 'FZ','Flydubai','SKYDUBAI','UAE'
UNION ALL SELECT 'G0','Ghana International Airlines','GHANA AIRLINES','Ghana'
UNION ALL SELECT 'G1','Gorkha Airlines','GORKHA AIRLINES','Nepal'
UNION ALL SELECT 'G2','Avirex','AVIREX-GABON','Gabon'
UNION ALL SELECT 'G3','City Connexion Airlines','CONNEXION','Burundi'
UNION ALL SELECT 'G3','Gol Transportes Aéreos','GOL TRANSPORTE','Brazil'
UNION ALL SELECT 'G4','Allegiant Air','ALLEGIANT','United States'
UNION ALL SELECT 'G5','China Express Airlines','CHINA EXPRESS','China'
UNION ALL SELECT 'G6','Guine Bissaur Airlines','BISSAU AIRLINES','Guinea-Bissau'
UNION ALL SELECT 'G6','Air Volga','GOUMRAK','Russia'
UNION ALL SELECT 'G7','Gandalf Airlines','Gandalf','Italy'
UNION ALL SELECT 'G7','GoJet Airlines','LINDBERGH','United States'
UNION ALL SELECT 'G8','Air Service Gabon','','Gabon'
UNION ALL SELECT 'G8','Enkor JSC','ENKOR','Russia'
UNION ALL SELECT 'G8','GoAir','GOAIR','India'
UNION ALL SELECT 'G8','Gujarat Airways','GUJARATAIR','India'
UNION ALL SELECT 'G9','Air Arabia','ARABIA','United Arab Emirates'
UNION ALL SELECT 'GA','Garuda Indonesia','INDONESIA','Indonesia'
UNION ALL SELECT 'GB','Airborne Express','ABEX','United States'
UNION ALL SELECT 'GB','ABX Air','ABEX','United States'
UNION ALL SELECT 'GC','Gambia International Airlines','GAMBIA INTERNATIONAL','Gambia'
UNION ALL SELECT 'GD','Air Alpha Greenland','AIR ALPHA','Denmark'
UNION ALL SELECT 'GE','TransAsia Airways','TransAsia','Taiwan'
UNION ALL SELECT 'GF','Gulf Air Bahrain','GULF BAHRAIN','Bahrain'
UNION ALL SELECT 'GG','Air Guyane','GREEN BIRD','French Guiana'
UNION ALL SELECT 'GG','Air Comores International','AIR COMORES','Comoros'
UNION ALL SELECT 'GG','Cargo 360','LONG-HAUL','United States'
UNION ALL SELECT 'GH','Ghana Airways','GHANA','Ghana'
UNION ALL SELECT 'GI','Itek Air','ITEK-AIR','Kyrgyzstan'
UNION ALL SELECT 'GJ','Compania Mexicargo','MEXICARGO','Mexico'
UNION ALL SELECT 'GJ','CDI Cargo Airlines','HUALONG','China'
UNION ALL SELECT 'GJ','Eurofly','E-FLY','Italy'
UNION ALL SELECT 'GK','Go One Airways','','United Kingdom'
UNION ALL SELECT 'GL','Air Greenland','GREENLAND','Denmark'
UNION ALL SELECT 'GL','Miami Air International','BISCAYNE','United States'
UNION ALL SELECT 'GM','Air Slovakia','SLOVAKIA','Slovakia'
UNION ALL SELECT 'GN','Air Gabon','GOLF NOVEMBER','Gabon'
UNION ALL SELECT 'GO','Kuzu Airlines Cargo','KUZU CARGO','Turkey'
UNION ALL SELECT 'GP','Gestair','GESTAIR','Spain'
UNION ALL SELECT 'GP','Palau Trans Pacific Airlines','TRANS PACIFIC','Palau'
UNION ALL SELECT 'GQ','Big Sky Airlines','BIG SKY','United States'
UNION ALL SELECT 'GR','Aurigny Air Services','AYLINE','United Kingdom'
UNION ALL SELECT 'GR','Gemini Air Cargo','GEMINI','United States'
UNION ALL SELECT 'GS','Air Foyle','FOYLE','United Kingdom'
UNION ALL SELECT 'GS','Grant Aviation','HOOT','United States'
UNION ALL SELECT 'GT','GB Airways','GEEBEE AIRWAYS','United Kingdom'
UNION ALL SELECT 'GV','Aero Flight','Aero Fox','Germany'
UNION ALL SELECT 'GW','Kuban Airlines','AIR KUBAN','Russia'
UNION ALL SELECT 'GX','JetX Airlines','JETBIRD','Iceland'
UNION ALL SELECT 'GX','Pacificair','','Philippines'
UNION ALL SELECT 'GY','Guyana Airways 2000','',''
UNION ALL SELECT 'GY','Tri-MG Intra Asia Airlines','TRILINES','Indonesia'
UNION ALL SELECT 'GZ','Air Rarotonga','AIR RAROTONGA','Cook Islands'
UNION ALL SELECT 'H2','Sky Airline','AEROSKY','Chile'
UNION ALL SELECT 'H4','Héli Sécurité Helicopter Airlines','','France'
UNION ALL SELECT 'H4','Inter Islands Airlines','','Cape Verde'
UNION ALL SELECT 'H5','Hola Airlines','HOLA','Spain'
UNION ALL SELECT 'H5','Mavial Magadan Airlines','Mavial','Russia'
UNION ALL SELECT 'H6','Hageland Aviation Services','HAGELAND','United States'
UNION ALL SELECT 'H7','Eagle Air','AFRICAN EAGLE','Uganda'
UNION ALL SELECT 'H8','Dalavia','DALAVIA','Russia'
UNION ALL SELECT 'H9','Air D''Ayiti','HAITI AVIA','Haiti'
UNION ALL SELECT 'H9','Izair','IZMIR','Turkey'
UNION ALL SELECT 'H9','Pegasus Airlines','SUNTURK','Turkey'
UNION ALL SELECT 'HA','Hawaiian Airlines','HAWAIIAN','United States'
UNION ALL SELECT 'HB','Harbor Airlines','HARBOR','United States'
UNION ALL SELECT 'HC','Aero-Tropics Air Services','','Australia'
UNION ALL SELECT 'HC','Holidays Czech Airlines','CZECH HOLIDAYS','Czech Republic'
UNION ALL SELECT 'HD','Air Holland','ORANGE','Netherlands'
UNION ALL SELECT 'HD','AIRDO','AIR DO','Japan'
UNION ALL SELECT 'HE','Luftfahrtgesellschaft Walter','WALTER','Germany'
UNION ALL SELECT 'HF','Hapagfly','HAPAG LLOYD','Germany'
UNION ALL SELECT 'HG','Niki','FLYNIKI','Austria'
UNION ALL SELECT 'HH','Hope Air','HOPE AIR','Canada'
UNION ALL SELECT 'HJ','Asian Express Airlines','FREIGHTEXPRESS','Australia'
UNION ALL SELECT 'HK','Four Star Aviation / Four Star Cargo','FOUR STAR','United States'
UNION ALL SELECT 'HM','Air Seychelles','SEYCHELLES','Seychelles'
UNION ALL SELECT 'HN','Heavylift Cargo Airlines','HEAVY CARGO','Australia'
UNION ALL SELECT 'HO','Antinea Airlines','ANTINEA','Algeria'
UNION ALL SELECT 'HP','America West Airlines','CACTUS','United States'
UNION ALL SELECT 'HP','Hawaiian Pacific Airlines','','United States'
UNION ALL SELECT 'HP','Pearl Airways','PEARL AIRWAYS','Haiti'
UNION ALL SELECT 'HP','Phoenix Airways','','Switzerland'
UNION ALL SELECT 'HQ','Harmony Airways','HARMONY','Canada'
UNION ALL SELECT 'HR','Hahn Air','ROOSTER','Germany'
UNION ALL SELECT 'HT','Aeromist-Kharkiv','AEROMIST','Ukraine'
UNION ALL SELECT 'HU','Hainan Airlines','HAINAN','China'
UNION ALL SELECT 'HV','Transavia Holland','TRANSAVIA','Netherlands'
UNION ALL SELECT 'HW','Hello','FLYHELLO','Switzerland'
UNION ALL SELECT 'HW','North-Wright Airways','NORTHWRIGHT','Canada'
UNION ALL SELECT 'HX','Hong Kong Airlines','BAUHINIA','Hong Kong SAR of China'
UNION ALL SELECT 'HY','Uzbekistan Airways','UZBEK','Uzbekistan'
UNION ALL SELECT 'HZ','Sat Airlines','SATCO','Kazakhstan'
UNION ALL SELECT 'I4','Interstate Airlines','FREEWAYAIR','Netherlands'
UNION ALL SELECT 'I6','Sky Eyes','SKY EYES','Thailand'
UNION ALL SELECT 'I7','Paramount Airways','PARAWAY','India'
UNION ALL SELECT 'I9','Indigo','INDIGO BLUE','United States'
UNION ALL SELECT 'I9','Air Italy','AIR ITALY','Italy'
UNION ALL SELECT 'IA','Iraqi Airways','IRAQI','Iraq'
UNION ALL SELECT 'IB','Iberia Airlines','IBERIA','Spain'
UNION ALL SELECT 'IC','Indian Airlines','INDAIR','India'
UNION ALL SELECT 'ID','Interlink Airlines','INTERLINK','South Africa'
UNION ALL SELECT 'IE','Solomon Airlines','SOLOMON','Solomon Islands'
UNION ALL SELECT 'IF','Islas Airways','PINTADERA','Spain'
UNION ALL SELECT 'IG','Meridiana','MERAIR','Italy'
UNION ALL SELECT 'IH','Falcon Aviation','','Sweden'
UNION ALL SELECT 'IH','Irtysh Air','IRTYSH AIRLINES','Kazakhstan'
UNION ALL SELECT 'II','IBC Airways','CHASQUI','United States'
UNION ALL SELECT 'IJ','Great Wall Airlines','GREAT WALL','China'
UNION ALL SELECT 'IK','Imair Airlines','IMPROTEX','Azerbaijan'
UNION ALL SELECT 'IK','Lankair','Lankair','Sri Lanka'
UNION ALL SELECT 'IM','Menajet','MENAJET','Lebanon'
UNION ALL SELECT 'IN','MAT Macedonian Airlines','MAKAVIO','Macedonia'
UNION ALL SELECT 'IO','Indonesian Airlines','INDO LINES','Indonesia'
UNION ALL SELECT 'IP','Atyrau Air Ways','EDIL','Kazakhstan'
UNION ALL SELECT 'IQ','Augsburg Airways','AUGSBURG-AIR','Germany'
UNION ALL SELECT 'IR','Iran Air','IRANAIR','Iran'
UNION ALL SELECT 'IT','Kingfisher Airlines','KINGFISHER','India'
UNION ALL SELECT 'IT','Kingfisher Airlines','KINGFISHER','India'
UNION ALL SELECT 'IV','Wind Jet','GHIBLI','Italy'
UNION ALL SELECT 'IW','AOM French Airlines','French Lines','France'
UNION ALL SELECT 'IX','Air India Express','EXPRESS INDIA','India'
UNION ALL SELECT 'IY','Yemenia','YEMENI','Yemen'
UNION ALL SELECT 'IZ','Arkia Israel Airlines','ARKIA','Israel'
UNION ALL SELECT 'J2','Azerbaijan Airlines','AZAL','Azerbaijan'
UNION ALL SELECT 'J3','Northwestern Air','POLARIS','Canada'
UNION ALL SELECT 'J4','Buffalo Airways','BUFFALO','Canada'
UNION ALL SELECT 'J6','AVCOM','AERO AVCOM','Russia'
UNION ALL SELECT 'J7','Centre-Avia','AVIACENTRE','Russia'
UNION ALL SELECT 'J7','Denim Air','DENIM','Netherlands'
UNION ALL SELECT 'J7','ValuJet Airlines','CRITTER','United States'
UNION ALL SELECT 'J8','Berjaya Air','BERJAYA','Malaysia'
UNION ALL SELECT 'J9','Guinee Airlines','GUINEE AIRLINES','Guinea'
UNION ALL SELECT 'J9','Jazeera Airways','JAZEERA','Kuwait'
UNION ALL SELECT 'JA','Air Bosna','AIR BOSNA','Bosnia and Herzegovina'
UNION ALL SELECT 'JA','B&H Airlines','Air Bosna','Bosnia and Herzegovina'
UNION ALL SELECT 'JB','Helijet','HELIJET','Canada'
UNION ALL SELECT 'JC','JAL Express','JANEX','Japan'
UNION ALL SELECT 'JE','Mango','TULCA','South Africa'
UNION ALL SELECT 'JF','Jetairfly','BEAUTY','Belgium'
UNION ALL SELECT 'JF','L.A.B. Flying Service','LAB','United States'
UNION ALL SELECT 'JH','Nordeste Linhas Aéreas Regionais','NORDESTE','Brazil'
UNION ALL SELECT 'JI','Midway Airlines (1993–2003)','MIDWAY','United States'
UNION ALL SELECT 'JJ','Aviogenex','GENEX','Serbia'
UNION ALL SELECT 'JJ','TAM Brazilian Airlines','TAM','Brazil'
UNION ALL SELECT 'JK','Spanair','SPANAIR','Spain'
UNION ALL SELECT 'JL','Japan Airlines','JAPANAIR','Japan'
UNION ALL SELECT 'JL','Japan Airlines Domestic','J-BIRD','Japan'
UNION ALL SELECT 'JM','Air Jamaica','JAMAICA','Jamaica'
UNION ALL SELECT 'JN','Excel Airways','EXPO','United Kingdom'
UNION ALL SELECT 'JO','JALways','JALWAYS','Japan'
UNION ALL SELECT 'JP','Adria Airways','ADRIA','Slovenia'
UNION ALL SELECT 'JQ','Jetstar Airways','JETSTAR','Australia'
UNION ALL SELECT 'JR','Aero California','AEROCALIFORNIA','Mexico'
UNION ALL SELECT 'JS','Air Koryo','AIR KORYO','Democratic People''s Republic of Korea'
UNION ALL SELECT 'JT','Lion Mentari Airlines','LION INTER','Indonesia'
UNION ALL SELECT 'JU','Jat Airways','JAT','Serbia'
UNION ALL SELECT 'JV','Bearskin Lake Air Service','BEARSKIN','Canada'
UNION ALL SELECT 'JW','Arrow Air','BIG A','United States'
UNION ALL SELECT 'JX','Jett8 Airlines Cargo','','Singapore'
UNION ALL SELECT 'JY','Air Turks and Caicos','KERRMONT','Turks and Caicos Islands'
UNION ALL SELECT 'JZ','Avia Express','SKY EXPRESS','Sweden'
UNION ALL SELECT 'JZ','Skyways Express','SKY EXPRESS','Sweden'
UNION ALL SELECT 'K2','Eurolot','EUROLOT','Poland'
UNION ALL SELECT 'K4','Kalitta Air','CONNIE','United States'
UNION ALL SELECT 'K5','Wings of Alaska','WINGS ALASKA','United States'
UNION ALL SELECT 'K6','Bravo Air Congo','BRAVO','Democratic Republic of the Congo'
UNION ALL SELECT 'K8','Airlink Zambia','','Zambia'
UNION ALL SELECT 'K9','Kalitta Charters','KALITTA','United States'
UNION ALL SELECT 'K9','Krylo Airlines','Krylo','Russia'
UNION ALL SELECT 'KA','Dragonair, Hong Kong Dragon Airlines','DRAGON','Hong Kong'
UNION ALL SELECT 'KB','Druk Air','ROYAL BHUTAN','Bhutan'
UNION ALL SELECT 'KC','Air Astana','ASTANALINE','Kazakhstan'
UNION ALL SELECT 'KD','Air Enterprise','AIR ENTERPRISE','France'
UNION ALL SELECT 'KD','KD Avia','KALININGRAD AIR','Russia'
UNION ALL SELECT 'KE','Korean Air','KOREANAIR','Republic of Korea'
UNION ALL SELECT 'KF','Blue1','BLUEFIN','Finland'
UNION ALL SELECT 'KG','LAI - Línea Aérea IAACA','AIR BARINAS','Venezuela'
UNION ALL SELECT 'KI','Air Atlantique','ATLANTIC','United Kingdom'
UNION ALL SELECT 'KI','Adam Air','ADAM SKY','Indonesia'
UNION ALL SELECT 'KJ','Asian Air','','Kyrgyzstan'
UNION ALL SELECT 'KJ','British Mediterranean Airways','BEE MED','United Kingdom'
UNION ALL SELECT 'KK','Atlasjet','ATLASJET','Turkey'
UNION ALL SELECT 'KL','KLM','KLM','Netherlands'
UNION ALL SELECT 'KM','Air Malta','AIR MALTA','Malta'
UNION ALL SELECT 'KN','China United Airlines','LIANHANG','China'
UNION ALL SELECT 'KO','Alaska Central Express','ACE AIR','United States'
UNION ALL SELECT 'KP','Kiwi International Air Lines','KIWI AIR','United States'
UNION ALL SELECT 'KQ','Kenya Airways','KENYA','Kenya'
UNION ALL SELECT 'KR','Comores Airlines','CONTICOM','Comoros'
UNION ALL SELECT 'KS','Peninsula Airways','PENINSULA','United States'
UNION ALL SELECT 'KU','Kuwait Airways','KUWAITI','Kuwait'
UNION ALL SELECT 'KV','Kavminvodyavia','AIR MINVODY','Russia'
UNION ALL SELECT 'KW','Wataniya Airways','WATANIYA','Kuwait'
UNION ALL SELECT 'KX','Cayman Airways','CAYMAN','Cayman Islands'
UNION ALL SELECT 'KY','Air São Tomé and Príncipe','EQUATORIAL','São Tomé and Príncipe'
UNION ALL SELECT 'KZ','Nippon Cargo Airlines','NIPPON CARGO','Japan'
UNION ALL SELECT 'L1','Lufthansa Systems','','Germany'
UNION ALL SELECT 'L2','Lynden Air Cargo','LYNDEN','United States'
UNION ALL SELECT 'L3','DHL de Guatemala','','Guatemala'
UNION ALL SELECT 'L3','LTU Austria','BILLA TRANSPORT','Austria'
UNION ALL SELECT 'L4','Lynx Aviation','SHASTA','United States'
UNION ALL SELECT 'L5','Lufttransport','LUFT TRANSPORT','Norway'
UNION ALL SELECT 'L6','Tbilaviamsheni','TBILAVIA','Georgia'
UNION ALL SELECT 'L7','Laoag International Airlines','LAOAG AIR','Philippines'
UNION ALL SELECT 'L7','Línea Aérea SAPSA','SAPSA','Chile'
UNION ALL SELECT 'L8','Air Luxor GB','LUXOR GOLF','Guinea-Bissau'
UNION ALL SELECT 'L9','Air Mali','AIR MALI','Mali'
UNION ALL SELECT 'L9','Bristow U.S. LLC','BRISTOW','United States'
UNION ALL SELECT 'L9','Teamline Air','Teamline','Austria'
UNION ALL SELECT 'LA','LAN Airlines','LAN','Chile'
UNION ALL SELECT 'LB','Lloyd Aéreo Boliviano','LLOYDAEREO','Bolivia'
UNION ALL SELECT 'LC','Logan Air','LOGAN','United Kingdom'
UNION ALL SELECT 'LC','Varig Logística','VELOG','Brazil'
UNION ALL SELECT 'LD','Air Hong Kong','AIR HONG KONG','Hong Kong'
UNION ALL SELECT 'LD','Línea Turística Aereotuy','AEREOTUY','Venezuela'
UNION ALL SELECT 'LF','FlyNordic','NORDIC','Sweden'
UNION ALL SELECT 'LG','Luxair','LUXAIR','Luxembourg'
UNION ALL SELECT 'LH','Lufthansa','LUFTHANSA','Germany'
UNION ALL SELECT 'LH','Lufthansa Cargo','LUFTHANSA CARGO','Germany'
UNION ALL SELECT 'LI','Leeward Islands Air Transport','LIAT','Antigua and Barbuda'
UNION ALL SELECT 'LJ','Sierra National Airlines','SELAIR','Sierra Leone'
UNION ALL SELECT 'LK','Air Luxor','AIRLUXOR','Portugal'
UNION ALL SELECT 'LL','Allegro','ALLEGRO','Mexico'
UNION ALL SELECT 'LM','Livingston','LIVINGSTON','Italy'
UNION ALL SELECT 'LN','Libyan Arab Airlines','LIBAIR','Libya'
UNION ALL SELECT 'LO','LOT Polish Airlines','POLLOT','Poland'
UNION ALL SELECT 'LP','LAN Peru','LANPERU','Peru'
UNION ALL SELECT 'LQ','Lebanese Air Transport','LAT','Lebanon'
UNION ALL SELECT 'LR','LACSA','LACSA','Costa Rica'
UNION ALL SELECT 'LS','Jet2.com','CHANNEX','United Kingdom'
UNION ALL SELECT 'LT','LTU International','LTU','Germany'
UNION ALL SELECT 'LU','LAN Express','LANEX','Chile'
UNION ALL SELECT 'LV','Albanian Airlines','ALBANIAN','Albania'
UNION ALL SELECT 'LW','Pacific Wings','TSUNAMI','United States'
UNION ALL SELECT 'LX','Swiss International Air Lines','SWISS','Switzerland'
UNION ALL SELECT 'LY','El Al Israel Airlines','ELAL','Israel'
UNION ALL SELECT 'LZ','Balkan Bulgarian Airlines','',''
UNION ALL SELECT 'M2','Mahfooz Aviation','MAHFOOZ','Gambia'
UNION ALL SELECT 'M3','ABSA Cargo','Turismo','Brazil'
UNION ALL SELECT 'M3','Air Service','AIR SKOPJE','Macedonia'
UNION ALL SELECT 'M3','North Flying','NORTH FLYING','Denmark'
UNION ALL SELECT 'M4','Nova Airline','NOVANILE','Sudan'
UNION ALL SELECT 'M5','Kenmore Air','KENMORE','United States'
UNION ALL SELECT 'M6','Amerijet International','AMERIJET','United States'
UNION ALL SELECT 'M7','MasAir','MAS CARGA','Mexico'
UNION ALL SELECT 'M7','Marsland Aviation','MARSLANDAIR','Sudan'
UNION ALL SELECT 'M7','Tropical Airways','','Haiti'
UNION ALL SELECT 'M8','Mekong Airlines','MEKONG AIRLINES','Cambodia'
UNION ALL SELECT 'M9','Motor Sich','MOTOR SICH','Ukraine'
UNION ALL SELECT 'MA','Malév Hungarian Airlines','MALEV','Hungary'
UNION ALL SELECT 'MB','Execair Aviation','CANADIAN EXECAIRE','Canada'
UNION ALL SELECT 'MB','MNG Airlines','BLACK SEA','Turkey'
UNION ALL SELECT 'MC','Air Mobility Command','REACH','United States'
UNION ALL SELECT 'MD','Air Madagascar','AIR MADAGASCAR','Madagascar'
UNION ALL SELECT 'ME','Middle East Airlines','CEDAR JET','Lebanon'
UNION ALL SELECT 'MF','Xiamen Airlines','XIAMEN AIR','China'
UNION ALL SELECT 'MG','Champion Air','CHAMPION AIR','United States'
UNION ALL SELECT 'MH','MASwings','MASWINGS','Malaysia'
UNION ALL SELECT 'MH','Malaysia Airlines','MALAYSIAN','Malaysia'
UNION ALL SELECT 'MI','SilkAir','SILKAIR','Singapore'
UNION ALL SELECT 'MJ','Líneas Aéreas Privadas Argentinas','LAPA','Argentina'
UNION ALL SELECT 'MK','Air Mauritius','AIRMAURITIUS','Mauritius'
UNION ALL SELECT 'ML','African Transport Trading and Investment Company','TRANATTICO','Sudan'
UNION ALL SELECT 'ML','Midway Airlines (1976–1991)','MIDWAY','United States'
UNION ALL SELECT 'MM','EuroAtlantic Airways','EUROATLANTIC','Portugal'
UNION ALL SELECT 'MM','SAM Colombia','SAM','Colombia'
UNION ALL SELECT 'MN','Comair','COMMERCIAL','South Africa'
UNION ALL SELECT 'MO','Abu Dhabi Amiri Flight','SULTAN','United Arab Emirates'
UNION ALL SELECT 'MO','Calm Air','CALM AIR','Canada'
UNION ALL SELECT 'MP','Martinair','MARTINAIR','Netherlands'
UNION ALL SELECT 'MQ','American Eagle Airlines','EAGLE FLIGHT','United States'
UNION ALL SELECT 'MR','Air Mauritanie','MIKE ROMEO','Mauritania'
UNION ALL SELECT 'MS','Egyptair','EGYPTAIR','Egypt'
UNION ALL SELECT 'MT','Thomas Cook Airlines','KESTREL','United Kingdom'
UNION ALL SELECT 'MU','China Eastern Airlines','CHINA EASTERN','China'
UNION ALL SELECT 'MV','Armenian International Airways','ARMENIA','Armenia'
UNION ALL SELECT 'MW','Maya Island Air','MYLAND','Belize'
UNION ALL SELECT 'MX','Mexicana de Aviación','MEXICANA','Mexico'
UNION ALL SELECT 'MY','Maxjet Airways','MAX-JET','United States'
UNION ALL SELECT 'MY','Midwest Airlines (Egypt)','','Egypt'
UNION ALL SELECT 'MZ','Merpati Nusantara Airlines','MERPATI','Indonesia'
UNION ALL SELECT 'N2','Dagestan Airlines','DAGAL','Russia'
UNION ALL SELECT 'N2','Kabo Air','KABO','Nigeria'
UNION ALL SELECT 'N3','Omskavia Airline','OMSK','Russia'
UNION ALL SELECT 'N4','Mountain Air Company','MOUNTAIN LEONE','Sierra Leone'
UNION ALL SELECT 'N4','National Airlines','','Chile'
UNION ALL SELECT 'N5','Kyrgyz Airlines','BERMET','Kyrgyzstan'
UNION ALL SELECT 'N5','Norfolk Air','','Norfolk Island'
UNION ALL SELECT 'N5','Skagway Air Service','SKAGWAY AIR','United States'
UNION ALL SELECT 'N6','Lagun Air','','Spain'
UNION ALL SELECT 'N6','Nuevo Continente','AERO CONTINENTE','Peru'
UNION ALL SELECT 'N7','National Airlines','RED ROCK','United States'
UNION ALL SELECT 'N8','Fika Salaama Airlines','SALAAMA','Uganda'
UNION ALL SELECT 'N9','North Coast Aviation','','Papua New Guinea'
UNION ALL SELECT 'NA','National Airlines','NATIONAL','United States'
UNION ALL SELECT 'NB','Sterling Airlines','STERLING','Denmark'
UNION ALL SELECT 'NC','National Jet Systems','NATIONAL JET','Australia'
UNION ALL SELECT 'NC','Northern Air Cargo','YUKON','United States'
UNION ALL SELECT 'NE','SkyEurope','RELAX','Slovakia'
UNION ALL SELECT 'NF','Air Vanuatu','AIR VAN','Vanuatu'
UNION ALL SELECT 'NG','Lauda Air','LAUDA AIR','Austria'
UNION ALL SELECT 'NH','All Nippon Airways','ALL NIPPON','Japan'
UNION ALL SELECT 'NI','Portugalia','PORTUGALIA','Portugal'
UNION ALL SELECT 'NK','Spirit Airlines','SPIRIT WINGS','United States'
UNION ALL SELECT 'NL','Shaheen Air International','SHAHEEN AIR','Pakistan'
UNION ALL SELECT 'NM','Air Madrid','ALADA AIR','Spain'
UNION ALL SELECT 'NM','Mount Cook Airlines','MOUNTCOOK','New Zealand'
UNION ALL SELECT 'NN','VIM Airlines','MOV AIR','Russia'
UNION ALL SELECT 'NO','Aus-Air','','Australia'
UNION ALL SELECT 'NO','Neos','MOONFLOWER','Italy'
UNION ALL SELECT 'NQ','Air Japan','AIR JAPAN','Japan'
UNION ALL SELECT 'NR','Pamir Airways','PAMIR','Afghanistan'
UNION ALL SELECT 'NT','Binter Canarias','BINTER','Spain'
UNION ALL SELECT 'NU','Japan Transocean Air','JAI OCEAN','Japan'
UNION ALL SELECT 'NV','Air Central','AIR CENTRAL','Japan'
UNION ALL SELECT 'NW','Northwest Airlines','NORTHWEST','United States'
UNION ALL SELECT 'NX','Air Macau','AIR MACAO','Macao'
UNION ALL SELECT 'NY','Air Iceland','FAXI','Iceland'
UNION ALL SELECT 'NZ','Air New Zealand','NEW ZEALAND','New Zealand'
UNION ALL SELECT 'NZ','Eagle Airways','EAGLE','New Zealand'
UNION ALL SELECT 'O2','Oceanic Airlines','','Guinea'
UNION ALL SELECT 'O4','Antrak Air','ANTRAK','Ghana'
UNION ALL SELECT 'O6','Oceanair','OCEANAIR','Brazil'
UNION ALL SELECT 'O7','Ozjet Airlines','AUSJET','Australia'
UNION ALL SELECT 'O8','Oasis Hong Kong Airlines','OASIS','Hong Kong'
UNION ALL SELECT 'OA','Olympic Air','OLYMPIC','Greece'
UNION ALL SELECT 'OA','Olympic Airlines','OLYMPIC','Greece'
UNION ALL SELECT 'OB','Astrakhan Airlines','AIR ASTRAKHAN','Russia'
UNION ALL SELECT 'OB','Austrian Airtransport','AUSTRIAN CHARTER','Austria'
UNION ALL SELECT 'OB','Oasis International Airlines','OASIS','Spain'
UNION ALL SELECT 'OE','Asia Overnight Express','ASIA OVERNIGHT','Philippines'
UNION ALL SELECT 'OF','Air Finland','AIR FINLAND','Finland'
UNION ALL SELECT 'OF','Enter Air','ENTER','Poland'
UNION ALL SELECT 'OF','Transports et Travaux Aériens de Madagascar','TAM AIRLINE','Madagascar'
UNION ALL SELECT 'OH','Comair','COMAIR','United States'
UNION ALL SELECT 'OJ','Overland Airways','OVERLAND','Nigeria'
UNION ALL SELECT 'OK','Czech Airlines','CSA','Czech Republic'
UNION ALL SELECT 'OL','Ostfriesische Lufttransport','OLTRA','Germany'
UNION ALL SELECT 'OM','MIAT Mongolian Airlines','MONGOL AIR','Mongolia'
UNION ALL SELECT 'ON','Nauru Air Corporation','AIR NAURU','Nauru'
UNION ALL SELECT 'ON','Our Airline','OUR AIRLINE','Nauru'
UNION ALL SELECT 'OO','SkyWest Airlines','SKYWEST','United States'
UNION ALL SELECT 'OP','Chalk''s International Airlines','CHALKS','United States'
UNION ALL SELECT 'OR','Arkefly','ARKEFLY','Netherlands'
UNION ALL SELECT 'OS','Austrian Airlines','AUSTRIAN','Austria'
UNION ALL SELECT 'OT','Aeropelican Air Services','PELICAN','Australia'
UNION ALL SELECT 'OU','Croatia Airlines','CROATIA','Croatia'
UNION ALL SELECT 'OW','Executive Airlines','EXECUTIVE EAGLE','United States'
UNION ALL SELECT 'OX','Orient Thai Airlines','ORIENT THAI','Thailand'
UNION ALL SELECT 'OY','Omni Air International','OMNI-EXPRESS','United States'
UNION ALL SELECT 'OZ','Asiana Airlines','ASIANA','Republic of Korea'
UNION ALL SELECT 'OZ','Ozark Air Lines','OZARK','United States'
UNION ALL SELECT 'P0','Proflight Commuter Services','','Zambia'
UNION ALL SELECT 'P3','Passaredo Transportes Aéreos','PASSAREDO','Brazil'
UNION ALL SELECT 'P5','AeroRepública','AEROREPUBLICA','Colombia'
UNION ALL SELECT 'P7','Russian Sky Airlines','RADUGA','Russia'
UNION ALL SELECT 'P8','Air Mekong','','Vietnam'
UNION ALL SELECT 'P8','Pantanal Linhas Aéreas','PANTANAL','Brazil'
UNION ALL SELECT 'P9','Nas Air','','Mali'
UNION ALL SELECT 'P9','Perm Airlines','PERM AIR','Russia'
UNION ALL SELECT 'P9','Peruvian Airlines','','Peru'
UNION ALL SELECT 'PA','Florida Coastal Airlines','FLORIDA COASTAL','United States'
UNION ALL SELECT 'PA','Pan American Airways','','United States'
UNION ALL SELECT 'PA','Pan American World Airways','CLIPPER','United States'
UNION ALL SELECT 'PC','Air Fiji','FIJIAIR','Fiji'
UNION ALL SELECT 'PC','Continental Airways','CONTAIR','Russia'
UNION ALL SELECT 'PD','Porter Airlines','PORTER AIR','Canada'
UNION ALL SELECT 'PE','Air Europe','AIR EUROPE','Italy'
UNION ALL SELECT 'PF','Palestinian Airlines','PALESTINIAN','Egypt'
UNION ALL SELECT 'PG','Bangkok Airways','BANGKOK AIR','Thailand'
UNION ALL SELECT 'PH','Polynesian Airlines','POLYNESIAN','Samoa'
UNION ALL SELECT 'PI','Piedmont Airlines (1948-1989)','PIEDMONT','United States'
UNION ALL SELECT 'PI','Sun Air (Fiji)','SUNFLOWER','Fiji'
UNION ALL SELECT 'PJ','Air Saint Pierre','SAINT-PIERRE','France'
UNION ALL SELECT 'PK','Pakistan International Airlines','PAKISTAN','Pakistan'
UNION ALL SELECT 'PL','Aeroperú','Aeroperu','Peru'
UNION ALL SELECT 'PL','Airstars','MOROZOV','Russia'
UNION ALL SELECT 'PM','Tropic Air','TROPISER','Belize'
UNION ALL SELECT 'PN','Pan American Airways','','United States'
UNION ALL SELECT 'PO','Polar Air Cargo','POLAR','United States'
UNION ALL SELECT 'PQ','AirAsia Philippines','','Philippines'
UNION ALL SELECT 'PR','Philippine Airlines','PHILIPPINE','Philippines'
UNION ALL SELECT 'PS','Ukraine International Airlines','UKRAINE INTERNATIONAL','Ukraine'
UNION ALL SELECT 'PS','Ukraine International Airlines','UKRAINE INTERNATIONAL','Ukraine'
UNION ALL SELECT 'PT','Capital Cargo International Airlines','CAPPY','United States'
UNION ALL SELECT 'PT','West Air Sweden','AIR SWEDEN','Sweden'
UNION ALL SELECT 'PU','PLUNA','PLUNA','Uruguay'
UNION ALL SELECT 'PV','PAN Air','SKYJET','Spain'
UNION ALL SELECT 'PV','St Barth Commuter','BLACK FIN','France'
UNION ALL SELECT 'PW','Precision Air','PRECISION AIR','Tanzania'
UNION ALL SELECT 'PX','Air Niugini','NUIGINI','Papua New Guinea'
UNION ALL SELECT 'PY','Surinam Airways','SURINAM','Suriname'
UNION ALL SELECT 'PZ','TAM Mercosur','PARAGUAYA','Paraguay'
UNION ALL SELECT 'Q3','Zambian Airways','ZAMBIANA','Zambia'
UNION ALL SELECT 'Q4','Mastertop Linhas Aéreas','','Brazil'
UNION ALL SELECT 'Q4','Starlink Aviation','STARLINK','Canada'
UNION ALL SELECT 'Q5','40-Mile Air','MILE-AIR','United States'
UNION ALL SELECT 'Q6','Aero Condor Peru','CONDOR-PERU','Peru'
UNION ALL SELECT 'Q8','Pacific East Asia Cargo Airlines','PAC-EAST CARGO','Philippines'
UNION ALL SELECT 'Q9','Afrinat International Airlines','AFRINAT','Gambia'
UNION ALL SELECT 'QB','Air Alma','AIR ALMA','Canada'
UNION ALL SELECT 'QB','Georgian National Airlines','NATIONAL','Georgia'
UNION ALL SELECT 'QC','Air Corridor','AIR CORRIDOR','Mozambique'
UNION ALL SELECT 'QD','Air Class Líneas Aéreas','ACLA','Uruguay'
UNION ALL SELECT 'QE','Crossair Europe','Cigogne','Switzerland'
UNION ALL SELECT 'QF','Eastern Australia Airlines','EASTERN','Australia'
UNION ALL SELECT 'QF','Qantas','QANTAS','Australia'
UNION ALL SELECT 'QF','Sunstate Airlines','SUNSTATE','Australia'
UNION ALL SELECT 'QH','Aero Leasing','AIR FLORIDA','United States'
UNION ALL SELECT 'QH','Kyrgyzstan','ALTYN AVIA','Kyrgyzstan'
UNION ALL SELECT 'QI','Cimber Sterling','CIMBER','Denmark'
UNION ALL SELECT 'QJ','Jet Airways','','United States'
UNION ALL SELECT 'QK','Air Canada Jazz','JAZZ','Canada'
UNION ALL SELECT 'QL','Aero Lanka','AERO LANKA','Sri Lanka'
UNION ALL SELECT 'QL','Línea Aérea de Servicio Ejecutivo Regional','LASER','Venezuela'
UNION ALL SELECT 'QM','Air Malawi','MALAWI','Malawi'
UNION ALL SELECT 'QN','Air Armenia','AIR ARMENIA','Armenia'
UNION ALL SELECT 'QO','Aeromexpress','AEROMEXPRESS','Mexico'
UNION ALL SELECT 'QO','Origin Pacific Airways','ORIGIN','New Zealand'
UNION ALL SELECT 'QQ','Alliance Airlines','UNITY','Australia'
UNION ALL SELECT 'QQ','Reno Air','RENO AIR','United States'
UNION ALL SELECT 'QR','Qatar Airways','QATARI','Qatar'
UNION ALL SELECT 'QS','African Safari Airways','ZEBRA','Kenya'
UNION ALL SELECT 'QS','Travel Service','SKYTRAVEL','Czech Republic'
UNION ALL SELECT 'QT','TAMPA','TAMPA','Colombia'
UNION ALL SELECT 'QU','UTair-Ukraine','UT Ukraine','Ukraine'
UNION ALL SELECT 'QV','Lao Airlines','LAO','Lao Peoples Democratic Republic'
UNION ALL SELECT 'QW','Blue Wings','BLUE WINGS','Germany'
UNION ALL SELECT 'QX','Horizon Air','HORIZON AIR','United States'
UNION ALL SELECT 'QY','European Air Transport','EUROTRANS','Belgium'
UNION ALL SELECT 'QZ','Indonesia AirAsia','WAGON AIR','Indonesia'
UNION ALL SELECT 'R0','Royal Airlines','ROYAL PAKISTAN','Pakistan'
UNION ALL SELECT 'R1','Sirin','',''
UNION ALL SELECT 'R2','Orenburg Airlines','ORENBURG','Russia'
UNION ALL SELECT 'R3','Armenian Airlines','ARMENIAN','Armenia'
UNION ALL SELECT 'R3','Aircompany Yakutia','AIR YAKUTIA','Russia'
UNION ALL SELECT 'R5','Jordan Aviation','JORDAN AVIATION','Jordan'
UNION ALL SELECT 'R5','Malta Air Charter','MALTA CHARTER','Malta'
UNION ALL SELECT 'R6','RACSA','','Guatemala'
UNION ALL SELECT 'R7','Aserca Airlines','AROSCA','Venezuela'
UNION ALL SELECT 'R8','Kyrgyzstan Airlines','KYRGYZ','Kyrgyzstan'
UNION ALL SELECT 'R9','Camai Air','AIR CAMAI','United States'
UNION ALL SELECT 'RA','Nepal Airlines','ROYAL NEPAL','Nepal'
UNION ALL SELECT 'RA','Royal Nepal Airlines','ROYAL NEPAL','Nepal'
UNION ALL SELECT 'RB','Air Srpska','Air Srpska','Bosnia and Herzegovina'
UNION ALL SELECT 'RB','Syrian Arab Airlines','SYRIANAIR','Syrian Arab Republic'
UNION ALL SELECT 'RC','Atlantic Airways','FAROELINE','Faroe Islands'
UNION ALL SELECT 'RD','Ryan International Airlines','RYAN INTERNATIONAL','United States'
UNION ALL SELECT 'RE','Aer Arann','AER ARANN','Ireland'
UNION ALL SELECT 'RF','Florida West International Airways','FLO WEST','United States'
UNION ALL SELECT 'RG','VRG Linhas Aéreas','VARIG','Brazil'
UNION ALL SELECT 'RH','Republic Express Airlines','PUBLIC EXPRESS','Indonesia'
UNION ALL SELECT 'RI','Mandala Airlines','MANDALA','Indonesia'
UNION ALL SELECT 'RJ','Royal Jordanian','JORDANIAN','Jordan'
UNION ALL SELECT 'RK','Royal Khmer Airlines','KHMER AIR','Cambodia'
UNION ALL SELECT 'RL','Rio Linhas Aéreas','RIO','Brazil'
UNION ALL SELECT 'RL','Royal Phnom Penh Airways','PHNOM-PENH AIR','Cambodia'
UNION ALL SELECT 'RO','Tarom','TAROM','Romania'
UNION ALL SELECT 'RP','Chautauqua Airlines','CHAUTAUQUA','United States'
UNION ALL SELECT 'RQ','Kam Air','KAMGAR','Afghanistan'
UNION ALL SELECT 'RR','Royal Air Force','RAFAIR','United Kingdom'
UNION ALL SELECT 'RS','Intercontinental de Aviación','CONTAVIA','Colombia'
UNION ALL SELECT 'RS','Royal Air Force of Oman','MAJAN','Oman'
UNION ALL SELECT 'RS','Sky Regional Airlines','MAPLE','Canada'
UNION ALL SELECT 'RU','AirBridge Cargo','AIRBRIDGE CARGO','Russia'
UNION ALL SELECT 'RU','SkyKing Turks and Caicos Airways','SKYKING','Turks and Caicos Islands'
UNION ALL SELECT 'RV','Caspian Airlines','CASPIAN','Iran'
UNION ALL SELECT 'RV','Africaone','AFRICAWORLD','The Gambia'
UNION ALL SELECT 'RW','Republic Airlines','BRICKYARD','United States'
UNION ALL SELECT 'RX','Aviaexpress','AVEX','Hungary'
UNION ALL SELECT 'RZ','Euro Exec Express','','Sweden'
UNION ALL SELECT 'S0','Slok Air Gambia','SLOK GAMBIA','Gambia'
UNION ALL SELECT 'S2','Air Sahara','SAHARA','India'
UNION ALL SELECT 'S3','Santa Barbara Airlines','SANTA BARBARA','Venezuela'
UNION ALL SELECT 'S4','SATA International','AIR AZORES','Portugal'
UNION ALL SELECT 'S5','Shuttle America','MERCURY','United States'
UNION ALL SELECT 'S5','Trast Aero','TRAST AERO','Kyrgyzstan'
UNION ALL SELECT 'S6','Star Air','','Denmark'
UNION ALL SELECT 'S7','S7 Airlines','SIBERIAN AIRLINES','Russia'
UNION ALL SELECT 'S8','Chari Aviation Services','CHARI SERVICE','Chad'
UNION ALL SELECT 'S8','Shovkoviy Shlyah','WAY AERO','Ukraine'
UNION ALL SELECT 'S9','East African Safari Air','DUMA','Kenya'
UNION ALL SELECT 'SA','South African Airways','SPRINGBOK','South Africa'
UNION ALL SELECT 'SB','Air Caledonie International','AIRCALIN','France'
UNION ALL SELECT 'SC','Shandong Airlines','SHANDONG','China'
UNION ALL SELECT 'SD','Sudan Airways','SUDANAIR','Sudan'
UNION ALL SELECT 'SE','XL Airways France','STARWAY','France'
UNION ALL SELECT 'SF','Tassili Airlines','TASSILI AIR','Algeria'
UNION ALL SELECT 'SG','JetsGo','JETSGO','Canada'
UNION ALL SELECT 'SG','Spicejet','SPICEJET','India'
UNION ALL SELECT 'SH','Fly Me Sweden','FLYBIRD','Sweden'
UNION ALL SELECT 'SI','Skynet Airlines','BLUEJET','Ireland'
UNION ALL SELECT 'SJ','Freedom Air','FREE AIR','New Zealand'
UNION ALL SELECT 'SK','Scandinavian Airlines','SCANDINAVIAN','Sweden, Denmark and Norway'
UNION ALL SELECT 'SK','SAS Braathens','SCANOR','Norway'
UNION ALL SELECT 'SL','Rio Sul Serviços Aéreos Regionais','RIO SUL','Brazil'
UNION ALL SELECT 'SM','Aberdeen Airways','','United Kingdom'
UNION ALL SELECT 'SM','Swedline Express','Starline','Sweden'
UNION ALL SELECT 'SN','Brussels Airlines','BEE-LINE','Belgium'
UNION ALL SELECT 'SO','Superior Aviation','SPEND AIR','United States'
UNION ALL SELECT 'SO','Sosoliso Airlines','SOSOLISO','Nigeria'
UNION ALL SELECT 'SO','Sunshine Airlines','',''
UNION ALL SELECT 'SP','SATA Air Acores','SATA','Portugal'
UNION ALL SELECT 'SQ','Singapore Airlines','SINGAPORE','Singapore'
UNION ALL SELECT 'SQ','Singapore Airlines Cargo','SINGCARGO','Singapore'
UNION ALL SELECT 'SR','Swissair','SWISSAIR','Switzerland'
UNION ALL SELECT 'SS','Corsairfly','CORSAIR','France'
UNION ALL SELECT 'ST','Germania','GERMANIA','Germany'
UNION ALL SELECT 'SU','Aeroflot Russian Airlines','AEROFLOT','Russia'
UNION ALL SELECT 'SV','Saudia','SAUDIA','Saudi Arabia'
UNION ALL SELECT 'SW','Air Namibia','NAMIBIA','Namibia'
UNION ALL SELECT 'SX','Skybus Airlines','SKYBUS','United States'
UNION ALL SELECT 'SY','Sun Country Airlines','SUN COUNTRY','United States'
UNION ALL SELECT 'SZ','Air Southwest','SWALLOW','United Kingdom'
UNION ALL SELECT 'T2','Thai Air Cargo','THAI CARGO','Thailand'
UNION ALL SELECT 'T3','Eastern Airways','EASTFLIGHT','United Kingdom'
UNION ALL SELECT 'T4','Hellas Jet','HELLAS JET','Greece'
UNION ALL SELECT 'T4','TRIP Linhas Aéreas','TRIP','Brazil'
UNION ALL SELECT 'T6','Tavrey Airlines','TAVREY','Ukraine'
UNION ALL SELECT 'T7','Twin Jet','TWINJET','France'
UNION ALL SELECT 'T9','TransMeridian Airlines','TRANS-MERIDIAN','United States'
UNION ALL SELECT 'T9','Thai Star Airlines','THAI STAR','Thailand'
UNION ALL SELECT 'TC','Air Tanzania','TANZANIA','Tanzania'
UNION ALL SELECT 'TD','Atlantis European Airways','','Armenia'
UNION ALL SELECT 'TD','Tulip Air','TULIPAIR','Netherland'
UNION ALL SELECT 'TE','FlyLal','LITHUANIA AIR','Lithuania'
UNION ALL SELECT 'TE','Skytaxi','IGUANA','Poland'
UNION ALL SELECT 'TF','Malmö Aviation','SCANWING','Sweden'
UNION ALL SELECT 'TG','Thai Airways International','THAI','Thailand'
UNION ALL SELECT 'TH','BA Connect','','United Kingdom'
UNION ALL SELECT 'TH','Transmile Air Services','TRANSMILE','Malaysia'
UNION ALL SELECT 'TI','Tol-Air Services','TOL AIR','United States'
UNION ALL SELECT 'TK','Turkish Airlines','TURKISH','Turkey'
UNION ALL SELECT 'TL','Airnorth','TOPEND','Australia'
UNION ALL SELECT 'TL','Trans Mediterranean Airlines','TANGO LIMA','Lebanon'
UNION ALL SELECT 'TM','Linhas Aéreas de Moçambique','MOZAMBIQUE','Mozambique'
UNION ALL SELECT 'TN','Air Tahiti Nui','TAHITI AIRLINES','France'
UNION ALL SELECT 'TO','President Airlines','','Cambodia'
UNION ALL SELECT 'TP','TAP Portugal','AIR PORTUGAL','Portugal'
UNION ALL SELECT 'TQ','Tandem Aero','TANDEM','Moldova'
UNION ALL SELECT 'TR','Transbrasil','TRANSBRASIL','Brazil'
UNION ALL SELECT 'TR','Tiger Airways','GO CAT','Singapore'
UNION ALL SELECT 'TS','Air Transat','AIR TRANSAT','Canada'
UNION ALL SELECT 'TT','Air Lithuania','KAUNAS','Lithuania'
UNION ALL SELECT 'TT','Tiger Airways Australia','GO CAT','Australia'
UNION ALL SELECT 'TU','Tunisair','TUNAIR','Tunisia'
UNION ALL SELECT 'TV','Virgin Express','VIRGIN EXPRESS','Belgium'
UNION ALL SELECT 'TW','Trans World Airlines','TWA','United States'
UNION ALL SELECT 'TX','Air Caraïbes','FRENCH WEST','France'
UNION ALL SELECT 'TY','Air Calédonie','AIRCAL','France'
UNION ALL SELECT 'TY','Iberworld','IBERWORLD','Spain'
UNION ALL SELECT 'TZ','air-taxi europe','TWINGOOSE','Germany'
UNION ALL SELECT 'TZ','ATA Airlines','AMTRAN','United States'
UNION ALL SELECT 'TZ','air-taxi europe','TWINGOOSE','Germany'
UNION ALL SELECT 'U2','easyJet','EASY','United Kingdom'
UNION ALL SELECT 'U2','United Feeder Service','FEEDER EXPRESS','United States'
UNION ALL SELECT 'U3','Avies','AVIES','Estonia'
UNION ALL SELECT 'U4','PMTair','MULTITRADE','Cambodia'
UNION ALL SELECT 'U5','USA3000 Airlines','GETAWAY','United States'
UNION ALL SELECT 'U6','Ural Airlines','SVERDLOVSK AIR','Russia'
UNION ALL SELECT 'U7','Air Uganda','UGANDA','Uganda'
UNION ALL SELECT 'U7','Northern Dene Airways','','Canada'
UNION ALL SELECT 'U7','USA Jet Airlines','JET USA','United States'
UNION ALL SELECT 'U8','Armavia','ARMAVIA','Armenia'
UNION ALL SELECT 'UA','United Airlines','UNITED','United States'
UNION ALL SELECT 'UB','Myanma Airways','UNIONAIR','Myanmar'
UNION ALL SELECT 'UD','Hex''Air','HEX AIRLINE','France'
UNION ALL SELECT 'UE','Nasair','NASAIRWAYS','Eritrea'
UNION ALL SELECT 'UE','Transeuropean Airlines','TRANSEURLINE','Russia'
UNION ALL SELECT 'UF','UM Airlines','UKRAINE MEDITERRANEE','Ukraine'
UNION ALL SELECT 'UG','SevenAir','S-BAR','United States'
UNION ALL SELECT 'UG','Tuninter','','Tunisia'
UNION ALL SELECT 'UH','US Helicopter','US-HELI','United States'
UNION ALL SELECT 'UH','US Helicopter Corporation','','United States'
UNION ALL SELECT 'UI','Eurocypria Airlines','EUROCYPRIA','Cyprus'
UNION ALL SELECT 'UL','SriLankan Airlines','SRILANKAN','Sri Lanka'
UNION ALL SELECT 'UM','Air Zimbabwe','AIR ZIMBABWE','Zimbabwe'
UNION ALL SELECT 'UN','Transaero Airlines','TRANSOVIET','Russia'
UNION ALL SELECT 'UO','Hong Kong Express Airways','HONGKONG SHUTTLE','Hong Kong SAR of China'
UNION ALL SELECT 'UP','Bahamasair','BAHAMAS','Bahamas'
UNION ALL SELECT 'UQ','O''Connor Airlines','OCONNOR','Australia'
UNION ALL SELECT 'US','US Airways','CACTUS','United States'
UNION ALL SELECT 'US','Unavia Suisse','','Switzerland'
UNION ALL SELECT 'US','USAir','','United States'
UNION ALL SELECT 'US','USAir Express','','United States'
UNION ALL SELECT 'UT','UTair Aviation','UTAIR','Russia'
UNION ALL SELECT 'UU','Air Austral','REUNION','France'
UNION ALL SELECT 'UX','Air Europa','EUROPA','Spain'
UNION ALL SELECT 'UY','Cameroon Airlines','CAM-AIR','Cameroon'
UNION ALL SELECT 'UZ','El-Buraq Air Transport','BURAQAIR','Libya'
UNION ALL SELECT 'V0','Conviasa','CONVIASA','Venezuela'
UNION ALL SELECT 'V2','Karat','AVIAKARAT','Russia'
UNION ALL SELECT 'V2','Vision Airlines','RUBY','United States'
UNION ALL SELECT 'V3','Carpatair','CARPATAIR','Romania'
UNION ALL SELECT 'V4','Reem Air','REEM AIR','Kyrgyzstan'
UNION ALL SELECT 'V5','Avolar Aerolíneas','AEROVOLAR','Mexico'
UNION ALL SELECT 'V5','DanubeWings','VIP TAXI','Slovakia'
UNION ALL SELECT 'V5','Royal Aruban Airlines','ROYAL ARUBAN','Aruba'
UNION ALL SELECT 'V7','Air Senegal International','AIR SENEGAL','Senegal'
UNION ALL SELECT 'V7','Volotea','',''
UNION ALL SELECT 'V8','ATRAN Cargo Airlines','ATRAN','Russian Federation'
UNION ALL SELECT 'V9','BAL Bashkirian Airlines','BASHKIRIAN','Russia'
UNION ALL SELECT 'V9','Star1 Airlines','STAR1','Lithuania'
UNION ALL SELECT 'VA','V Australia Airlines','VEE-OZ','Australia'
UNION ALL SELECT 'VA','Viasa','','Venezuela'
UNION ALL SELECT 'VB','Aeroenlaces Nacionales','AEROENLACES','Mexico'
UNION ALL SELECT 'VC','Ocean Airlines','OCEANCARGO','Italy'
UNION ALL SELECT 'VC','Voyageur Airways','VOYAGEUR','Canada'
UNION ALL SELECT 'VD','Air Liberté','AIR LIBERTE','France'
UNION ALL SELECT 'VD','Kunpeng Airlines','KUNPENG','China'
UNION ALL SELECT 'VD','SwedJet Airways','BLACKBIRD','Sweden'
UNION ALL SELECT 'VE','Avensa','AVENSA','Venezuela'
UNION ALL SELECT 'VE','EUjet','UNION JET','Ireland'
UNION ALL SELECT 'VE','Volare Airlines','VOLA','Italy'
UNION ALL SELECT 'VF','Valuair','VALUAIR','Singapore'
UNION ALL SELECT 'VG','VLM Airlines','RUBENS','Belgium'
UNION ALL SELECT 'VH','Aeropostal Alas de Venezuela','AEROPOSTAL','Venezuela'
UNION ALL SELECT 'VI','Volga-Dnepr Airlines','VOLGA-DNEPR','Russia'
UNION ALL SELECT 'VJ','Africa Airways','AFRIWAYS','Benin'
UNION ALL SELECT 'VJ','Jatayu Airlines','JATAYU','Indonesia'
UNION ALL SELECT 'VK','Virgin Nigeria Airways','VIRGIN NIGERIA','Nigeria'
UNION ALL SELECT 'VL','Air VIA','','Bulgaria'
UNION ALL SELECT 'VM','Viaggio Air','VIAGGIO','Bulgaria'
UNION ALL SELECT 'VN','Vietnam Airlines','VIET NAM AIRLINES','Vietnam'
UNION ALL SELECT 'VO','Austrian Arrows','TYROLEAN','Austria'
UNION ALL SELECT 'VP','VASP','VASP','Brazil'
UNION ALL SELECT 'VR','TACV','CABOVERDE','Cape Verde'
UNION ALL SELECT 'VS','Virgin Atlantic Airways','VIRGIN','United Kingdom'
UNION ALL SELECT 'VT','Air Tahiti','AIR TAHITI','French Polynesia'
UNION ALL SELECT 'VU','Air Ivoire','AIRIVOIRE','Ivory Coast'
UNION ALL SELECT 'VV','Aerosvit Airlines','AEROSVIT','Ukraine'
UNION ALL SELECT 'VW','Aeromar','TRANS-AEROMAR','Mexico'
UNION ALL SELECT 'VX','ACES Colombia','ACES','Colombia'
UNION ALL SELECT 'VX','Virgin America','REDWOOD','United States'
UNION ALL SELECT 'VY','Formosa Airlines','','Taiwan'
UNION ALL SELECT 'VY','Vueling Airlines','VUELING','Spain'
UNION ALL SELECT 'VZ','MyTravel Airways','KESTREL','United Kingdom'
UNION ALL SELECT 'W1','WDL Aviation','WDL','Germany'
UNION ALL SELECT 'W2','Canadian Western Airlines','CANADIAN WESTERN','Canada'
UNION ALL SELECT 'W3','Flyhy Cargo Airlines','FLY HIGH','Thailand'
UNION ALL SELECT 'W4','Aero Services Executive','BIRD EXPRESS','France'
UNION ALL SELECT 'W5','Mahan Air','MAHAN AIR','Iran'
UNION ALL SELECT 'W6','Wizz Air','WIZZAIR','Hungary'
UNION ALL SELECT 'W8','Cargojet Airways','CARGOJET','Canada'
UNION ALL SELECT 'W9','Abelag Aviation','ABG','Belgium'
UNION ALL SELECT 'W9','Air Bagan','AIR BAGAN','Myanmar'
UNION ALL SELECT 'W9','Eastwind Airlines','STINGER','United States'
UNION ALL SELECT 'WA','KLM Cityhopper','CITY','Netherlands'
UNION ALL SELECT 'WA','Western Airlines','WESTERN','United States'
UNION ALL SELECT 'WB','Rwandair Express','RWANDAIR','Rwanda'
UNION ALL SELECT 'WC','Islena De Inversiones','','Honduras'
UNION ALL SELECT 'WD','DAS Air Cargo','DAIRAIR','Uganda'
UNION ALL SELECT 'WD','Amsterdam Airlines','AMSTEL','Netherlands'
UNION ALL SELECT 'WE','Centurion Air Cargo','CHALLENGE CARGO','United States'
UNION ALL SELECT 'WF','Widerøe','WIDEROE','Norway'
UNION ALL SELECT 'WG','Sunwing Airlines','SUNWING','Canada'
UNION ALL SELECT 'WH','China Northwest Airlines','CHINA NORTHWEST','China'
UNION ALL SELECT 'WH','WebJet Linhas Aéreas','WEB-BRASIL','Brazil'
UNION ALL SELECT 'WK','American Falcon','AMERICAN FALCON','Argentina'
UNION ALL SELECT 'WK','Edelweiss Air','EDELWEISS','Switzerland'
UNION ALL SELECT 'WN','Southwest Airlines','SOUTHWEST','United States'
UNION ALL SELECT 'WO','World Airways','WORLD','United States'
UNION ALL SELECT 'WR','Royal Tongan Airlines','TONGA ROYAL','Tonga'
UNION ALL SELECT 'WS','WestJet','WESTJET','Canada'
UNION ALL SELECT 'WT','Wasaya Airways','WASAYA','Canada'
UNION ALL SELECT 'WV','Swe Fly','FLYING SWEDE','Sweden'
UNION ALL SELECT 'WW','Bmibaby','BABY','United Kingdom'
UNION ALL SELECT 'WX','CityJet','CITY-IRELAND','Ireland'
UNION ALL SELECT 'WY','Oman Air','OMAN AIR','Oman'
UNION ALL SELECT 'WZ','West African Airlines','','Benin'
UNION ALL SELECT 'X3','Hapag-Lloyd Express (TUIfly)','YELLOW CAB','Germany'
UNION ALL SELECT 'X7','Chitaavia','CHITA','Russia'
UNION ALL SELECT 'XF','Vladivostok Air','VLADAIR','Russia'
UNION ALL SELECT 'XJ','Mesaba Airlines','MESABA','United States'
UNION ALL SELECT 'XK','Corse-Mediterranee','CORSICA','France'
UNION ALL SELECT 'XL','Aerolane','AEROLANE','Ecuador'
UNION ALL SELECT 'XM','J-Air','J AIR','Japan'
UNION ALL SELECT 'XO','LTE International Airways','FUN JET','Spain'
UNION ALL SELECT 'XP','Western','RUBY MOUNTAIN',''
UNION ALL SELECT 'XP','Xtra Airways','CASINO EXPRESS','United States'
UNION ALL SELECT 'XQ','SunExpress','SUNEXPRESS','Turkey'
UNION ALL SELECT 'XS','SITA','','Belgium'
UNION ALL SELECT 'XT','Air Exel','EXEL COMMUTER','Netherlands'
UNION ALL SELECT 'XT','SkyStar Airways','SKY YOU','Thailand'
UNION ALL SELECT 'Y2','Flyglobespan','GLOBESPAN','United Kingdom'
UNION ALL SELECT 'Y4','Volaris','VOLARIS','Mexico'
UNION ALL SELECT 'Y5','Pace Airlines','PACE','United States'
UNION ALL SELECT 'Y6','Batavia Air','BATAVIA','Indonesia'
UNION ALL SELECT 'Y8','Yangtze River Express','YANGTZE RIVER','China'
UNION ALL SELECT 'Y9','Kish Air','KISHAIR','Iran'
UNION ALL SELECT 'YD','Cologne Air Transport GmbH','','Germany'
UNION ALL SELECT 'YE','Aryan Cargo Express','','India'
UNION ALL SELECT 'YH','West Caribbean Airways','WEST','Colombia'
UNION ALL SELECT 'YK','Cyprus Turkish Airlines','AIRKIBRIS','Turkey'
UNION ALL SELECT 'YL','Yamal Airlines','YAMAL','Russia'
UNION ALL SELECT 'YM','Montenegro Airlines','MONTENEGRO','Montenegro'
UNION ALL SELECT 'YS','Régional Compagnie Aérienne Européenne','REGIONAL EUROPE','France'
UNION ALL SELECT 'YT','Air Togo','AIR TOGO','Togo'
UNION ALL SELECT 'YU','Dominair','DOMINAIR','Dominican Republic'
UNION ALL SELECT 'YV','Mesa Airlines','AIR SHUTTLE','United States'
UNION ALL SELECT 'YW','Air Nostrum','AIR NOSTRUM','Spain'
UNION ALL SELECT 'YX','Midwest Airlines','MIDEX','United States'
UNION ALL SELECT 'Z3','Avient Aviation','AVAVIA','Zimbabwe'
UNION ALL SELECT 'Z4','Zoom Airlines','ZOOM','Canada'
UNION ALL SELECT 'Z5','GMG Airlines','GMG','Bangladesh'
UNION ALL SELECT 'Z7','ADC Airlines','ADCO','Nigeria'
UNION ALL SELECT 'Z8','Amaszonas','','Bolivia'
UNION ALL SELECT 'ZA','AccessAir','CYCLONE','United States'
UNION ALL SELECT 'ZA','Interavia Airlines','ASTAIR','Russia'
UNION ALL SELECT 'ZB','Air Bourbon','BOURBON','Reunion'
UNION ALL SELECT 'ZB','Monarch Airlines','MONARCH','United Kingdom'
UNION ALL SELECT 'ZE','Líneas Aéreas Azteca','LINEAS AZTECA','Mexico'
UNION ALL SELECT 'ZG','Viva Macau','JACKPOT','Macao'
UNION ALL SELECT 'ZH','Shenzhen Airlines','SHENZHEN AIR','China'
UNION ALL SELECT 'ZI','Aigle Azur','AIGLE AZUR','France'
UNION ALL SELECT 'ZK','Great Lakes Airlines','LAKES AIR','United States'
UNION ALL SELECT 'ZL','Regional Express','REX','Australia'
UNION ALL SELECT 'ZP','Silk Way Airlines','SILK LINE','Azerbaijan'
UNION ALL SELECT 'ZS','Azzurra Air','AZZURRA','Italy'
UNION ALL SELECT 'ZS','Sama Airlines','NAJIM','Saudi Arabia'
UNION ALL SELECT 'ZT','Titan Airways','ZAP','United Kingdom'
UNION ALL SELECT 'ZU','Helios Airways','HELIOS','Cyprus'
UNION ALL SELECT 'ZV','Air Midwest','AIR MIDWEST','United States'
UNION ALL SELECT 'ZW','Air Wisconsin','AIR WISCONSIN','United States'
UNION ALL SELECT 'ZX','Air BC','AIRCOACH','Canada'
UNION ALL SELECT 'ZX','Air Georgian','GEORGIAN','Canada'
UNION ALL SELECT 'ZY','Sky Airlines','ANTALYA BIRD','Turkey'
UNION ALL SELECT 'XX', 'Dummy Airlines', 'DUMMY', 'SQL-Land'
) a (AirlineCode, AirlineName, CallSign, Country)
) b
WHERE n = 1